export const PLUGIN_ID = "git4zotero@paper-version.local";
export const PLUGIN_NAME = "git4zotero";
export const FTL_FILE = "git4zotero.ftl";
export const STYLE_ID = "git4zotero-style";
export const SECTION_ID = "git4zotero-paper-versions";
export const ICON_16 = "chrome/content/icons/paper-version-16.png";
export const ICON_20 = "chrome/content/icons/paper-version-20.png";
export const PREFERENCES_XHTML = "chrome/content/preferences.xhtml";
export const PREFERENCES_SCRIPT = "chrome/content/preferences.mjs";
export const PREFERENCES_STYLE = "chrome/content/preferences.css";
export const SUPPORTED_EXTENSIONS = [".docx", ".doc"];

export const PREFS = Object.freeze({
  gitPath: "extensions.git4zotero.gitPath",
  defaultVersionNote: "extensions.git4zotero.defaultVersionNote",
  autoSafetyVersion: "extensions.git4zotero.autoSafetyVersion",
  archiveExportDirectory: "extensions.git4zotero.archiveExportDirectory",
  lastError: "extensions.git4zotero.lastError"
});

export const UI_TEXT = {
  locale: "zh-CN",
  dateLocale: "zh-CN",
  colon: "：",
  semicolon: "；",
  listComma: "，",
  fullStop: "。",
  menuRoot: "论文版本",
  preferencePaneLabel: "Git",
  loading: "正在读取论文版本信息…",
  noItem: "请选择一个 Zotero 条目。",
  gitUnavailable: "Git 不可用",
  gitUnavailableDetail: "未检测到可用的 Git。请安装 Git，或配置 Git 可执行文件路径。",
  gitPathNotFound: "未找到 Git 可执行文件。请在“论文版本管理”设置中填写完整 git.exe 路径，例如 C:\\Program Files\\Git\\cmd\\git.exe。",
  gitPathActionRequired: "未找到 Git 可执行文件，请填写完整 git.exe 路径",
  gitConfigured: "Git 路径已配置",
  configureGit: "配置 Git 路径",
  refreshPanel: "刷新",
  refreshingPanel: "正在刷新…",
  noDocument: "未找到可管理的论文文件",
  noDocumentDetail: "请为当前条目添加 .docx 或 .doc 附件。",
  rightClickHint: "请在条目列表中右键条目或论文附件进行版本操作。",
  notEnabled: "尚未启用版本管理",
  notEnabledDetail: "只有通过右键菜单启用的条目才会被 git4zotero 跟踪。未启用条目不会创建 Git 仓库，也不会保存或恢复版本。",
  enableManagement: "启用版本管理",
  enablingManagement: "正在启用版本管理…",
  enableSuccess: "已为当前条目启用论文版本管理。",
  disableManagement: "停用版本管理",
  disablingManagement: "正在停用版本管理…",
  disableConfirmTitle: "停用版本管理",
  disableConfirmMessage: "停用后不会删除已有版本历史，但当前条目将不再允许检查、创建或恢复版本。确定继续吗？",
  disableSuccess: "已停用当前条目的论文版本管理。",
  itemNotEnabledError: "当前条目尚未启用论文版本管理。",
  currentFile: "当前论文文件",
  createVersion: "创建版本",
  creatingVersion: "正在创建版本…",
  checkChanges: "检查修改",
  checkingChanges: "正在检查修改…",
  lastCheck: "最近检查",
  neverChecked: "尚未检查修改。",
  workingTree: "Git 工作树",
  workingTreeClean: "工作树无未提交修改。",
  workingTreeUninitialized: "尚未创建 Git 仓库。",
  versionHistory: "版本历史",
  restoreVersion: "恢复此版本",
  restoringVersion: "正在恢复版本…",
  emptyHistory: "尚未创建版本。",
  notePlaceholder: "输入本次版本说明，例如：完成引言修改",
  defaultNote: "论文版本",
  safetyNotePrefix: "恢复前自动备份",
  restoreConfirmTitle: "恢复论文版本",
  restoreConfirmMessage: "恢复会先自动备份当前文件，然后用所选版本覆盖当前论文附件。确定继续吗？",
  createSuccess: "版本已创建。",
  noChangesToSave: "未检测到修改，无需创建新版本。",
  restoreSuccess: "版本已恢复。",
  restoreSafetyBackup: "恢复前当前文件备份",
  restorePreflightMissing: "当前论文文件不存在，无法恢复。",
  restorePreflightUnreadable: "当前论文文件不可读取，无法安全恢复。",
  restorePreflightUnwritable: "当前论文文件所在目录不可写，无法安全恢复。",
  restorePreflightWritable: "当前文件目录可写",
  restorePreflightBlocked: "恢复预检未通过，已阻止恢复。",
  restorePreflightWarning: "恢复预检通过，但存在需要注意的风险。请先保存并关闭 Word/WPS/LibreOffice 后再继续。",
  restorePreflightOk: "恢复预检通过。",
  restorePreflightChanged: "确认后当前论文文件已发生变化，已取消恢复。请重新执行恢复操作。",
  restoreTargetHash: "目标版本文件 hash",
  restoreTargetHashUnknown: "该历史版本未记录文件 hash；恢复时仍会校验实际 Git 文件。",
  restorePreflightTitle: "恢复前安全检查",
  restorePreflightConfirmIntro: "请确认以下恢复信息。若文件仍在 Word/WPS/LibreOffice 中打开，请先保存并关闭后再继续。",
  restorePreflightErrors: "发现 {count} 个阻止恢复的问题。",
  restorePreflightWarnings: "发现 {count} 个需要注意的问题。",
  restorePreflightProceed: "继续恢复会先备份当前文件，再替换为目标版本。确定继续吗？",
  restoreFailedWithBackup: "恢复失败，当前文件已保留备份。",
  restoreHashMismatch: "恢复后的文件校验失败，已尝试回滚到恢复前状态。",
  repositoryHealth: "仓库健康",
  repositoryHealthOk: "版本仓库状态正常。",
  repositoryHealthWarning: "版本仓库存在需要关注的问题。",
  repositoryHealthError: "版本仓库存在影响恢复的问题。",
  operationFailed: "操作失败",
  errorUserActionableTitle: "需要用户处理",
  errorGitTitle: "Git 问题",
  errorFileStateTitle: "文件状态问题",
  errorInternalTitle: "插件内部错误",
  errorUserActionableSuggestion: "请按提示完成选择、启用版本管理或先检查修改后再操作。",
  errorGitSuggestion: "请确认 Git 已安装，并在设置页填写正确的 Git 可执行文件路径后重新测试。",
  errorFileStateSuggestion: "请确认论文文件存在、已保存，且未被 Word/WPS/LibreOffice 占用。",
  errorInternalSuggestion: "请复制诊断信息并在 issue 中附上操作步骤，便于定位问题。",
  actionCompleted: "操作完成。",
  menuUnavailable: "论文版本操作不可用",
  menuMultiSelectUnsupported: "请只选择一个 Zotero 条目或论文附件。",
  menuCreatePromptTitle: "创建论文版本",
  menuCreatePromptMessage: "请输入本次版本说明。",
  createPreviewTitle: "创建版本前确认",
  createPreviewConfirmMessage: "请确认本次将保存的版本信息。",
  createPreviewProceed: "确定创建这个版本吗？",
  createPreviewNoChanges: "未检测到可保存的变化。",
  createPreviewDocWarning: ".doc 仅做文件级跟踪，本次版本不会生成正文级差异。",
  menuRestorePromptTitle: "恢复论文版本",
  menuRestorePromptMessage: "请选择要恢复的版本。",
  menuExportSummary: "导出版本摘要",
  menuExportSummaryLabel: "导出版本摘要...",
  menuExportScopeMessage: "请选择要导出的内容。",
  menuExportFormatMessage: "请选择导出格式。",
  exportScopeHistory: "完整版本历史",
  exportScopeLastCheck: "最近检查差异",
  exportFormatMarkdown: "Markdown",
  exportFormatText: "纯文本",
  exportSuccess: "版本摘要已导出。",
  exportNoLastCheck: "尚未检查修改，无法导出最近检查差异。",
  menuNoVersions: "当前条目尚未创建版本。",
  menuStatusLoading: "正在读取论文版本状态...",
  menuStatusNoSelection: "请选择一个条目或论文附件。",
  menuStatusReady: "论文版本可用。",
  menuStatusNoHistory: "尚未创建版本。",
  menuDisabledReasonPrefix: "不可用",
  menuConfigureGit: "配置 Git 路径...",
  invalidCommit: "版本标识无效，已取消恢复。",
  promptGitTitle: "配置 Git 路径",
  promptGitMessage: "请输入 Git 可执行文件路径。留空表示使用系统 PATH 中的 git。",
  contentModeDocx: ".docx 正文级识别",
  contentModeFileOnly: "文件级跟踪",
  docFileOnlyTracking: ".doc 仅支持文件级跟踪，可创建和恢复版本，但不解析正文差异。",
  versionDetails: "版本详情",
  savedBeforeCheck: "请先在 Word/WPS/LibreOffice 中保存论文文件，再回到 Zotero 检查修改或创建版本。",

  stateDirty: "有未提交修改",
  stateClean: "工作树干净",
  stateUnchecked: "尚未检查工作树",
  stateEnabled: "已启用",
  stateDisabled: "未启用",
  stateGitAvailable: "Git 可用",
  stateGitUnavailable: "Git 不可用",
  stateLatestVersion: "最近版本",
  stateLastCheck: "最近检查",
  stateWorkingTree: "未提交修改",
  statusCardsTitle: "当前状态",
  stateVersionCount: "{count} 个版本",
  stateLatest: "最新 {value}",
  workflow: "工作流",
  workflowAddAttachmentTitle: "添加论文附件",
  workflowAddAttachmentDetail: "为当前条目添加 .docx 或 .doc 文件后再进行版本管理。",
  workflowEnableTitle: "启用版本管理",
  workflowEnableDetail: "右键条目或附件，选择“{menuRoot} → {enableManagement}”。",
  workflowCheckCreateFirstTitle: "检查修改并创建首个版本",
  workflowCheckCreateFirstCurrentTitle: "检查并创建首个版本",
  workflowCheckCreateFirstDetail: "启用后使用“{checkChanges}”确认差异，再使用“{createVersion}”。",
  workflowEnabledTitle: "版本管理已启用",
  workflowConfigureGitTitle: "配置 Git",
  workflowConfigureGitDetail: "打开设置页填写 Git 路径，或右键选择“{menuConfigureGit}”。",
  workflowCheckCurrentTitle: "检查当前修改",
  workflowCheckSavedDetail: "保存论文文件后，右键选择“{checkChanges}”；确认无误后选择“{createVersion}”。",
  workflowRestoreHistoryTitle: "恢复历史版本",
  workflowRestoreHistoryAvailable: "已有 {count} 个版本，可右键选择“{restoreVersionMenu}”。",
  workflowRestoreHistoryEmpty: "创建首个版本后，这里会显示可恢复的历史。",
  workflowWorkingTreeTitle: "工作树状态",
  workflowWorkingTreeDirty: "检测到未提交修改，创建版本后会进入历史记录。",
  contentSummaryDocx: "正文 {paragraphCount} 段 · {wordCount} 字/词",
  additionalIssues: "另有 {count} 个问题未展开。",
  versionNoteLabel: "版本说明",
  createdAtLabel: "创建时间",
  gitHashLabel: "Git hash",
  fileNameLabel: "文件名",
  fileSizeLabel: "文件大小",
  versionTypeLabel: "版本类型",
  safetyBackupLabel: "安全备份",
  changeSummaryLabel: "变化摘要",
  trackingModeLabel: "跟踪方式",
  safetyBackupYes: "是，恢复前自动备份",
  safetyBackupNo: "否",
  versionKindSafety: "自动备份",
  versionKindGit: "Git 历史",
  versionKindManual: "手动",
  versionKindSafetyFull: "恢复前自动备份",
  versionKindManualFull: "手动版本",
  omittedParagraphChanges: "另有 {count} 处段落变化未展开。",
  omittedParagraphChangesDialog: "另有 {count} 处段落变化未在弹窗中展开。",
  concreteChanges: "具体修改",
  changeBefore: "修改前",
  changeAfter: "修改后",
  changeDeleted: "删除",
  changeAdded: "新增",
  changeKindAdded: "新增段落",
  changeKindDeleted: "删除段落",
  changeKindModified: "修改段落",
  changeKindParagraph: "段落变化",
  paragraphIndex: "第 {index} 段",
  emptyParagraph: "（空段落）",

  sourceDocument: "正文",
  sourceFootnotes: "脚注",
  sourceEndnotes: "尾注",
  sourceHeader: "页眉",
  sourceFooter: "页脚",
  tableLabel: "表格",
  tableWithIndex: "表格 {index}",
  untitledBody: "无标题正文",
  changeCount: "{count} 处变化",

  firstDocxSummary: "首次创建版本，将保存当前 .docx 正文内容快照。",
  noChanges: "未检测到修改。",
  fileOnlyFormattingSummary: "正文内容未变化，仅检测到格式、样式、元数据或 Word 内部状态变化。",
  docxContentChanged: "正文内容已修改",
  addedParagraphs: "新增 {count} 段",
  deletedParagraphs: "删除 {count} 段",
  modifiedParagraphs: "修改 {count} 段",
  wordDelta: "字数变化 {value}",
  firstDocxUnreadableSummary: "首次创建版本，当前 .docx 暂不可解析，已保存文件级快照。",
  firstFileLevelSummary: "首次创建版本，{extension} 将保存文件级快照。",
  thisFormat: "该格式",
  docxReadFailedSummary: "当前 .docx 暂不可解析，已按文件级快照保存；请确认文件已由 Word/WPS 完整保存。",
  genericFileLevelSummary: "当前格式仅支持文件级识别：文件内容已变化，但不解析正文差异。",
  noDocxByteReader: "当前环境无法读取 docx 文件字节。",
  missingDocumentXml: "无法识别 docx 正文：缺少 word/document.xml。",
  noComparableText: "未在 docx 正文、脚注或尾注中识别到可比对文本。请确认文件已保存且包含正文。",
  invalidDocxZipDirectory: "无效的 docx 压缩目录。",
  invalidDocxLocalHeader: "docx 条目 {name} 的本地头无效。",
  unsupportedCompressionMethod: "暂不支持的压缩方式：{method}",
  docxEntryInflateFailed: "无法解析 docx 条目 {name} 的压缩内容：{message}",
  docxEntrySizeMismatch: "docx 条目 {name} 解压长度不符：期望 {expected}，实际 {actual}。",
  missingZipCentralDirectory: "无法读取 docx：未找到 ZIP 中央目录。",
  compressedDataUnexpectedEnd: "压缩数据意外结束。",

  invalidTrackedPath: "跟踪文件路径无效，已取消恢复。",
  gitStatusFailed: "无法读取 Git 工作树状态。",
  gitCommandFailed: "Git 命令失败：git {args}",
  processExitCode: "退出码 {code}",
  saveFileTitle: "保存文件",
  saveDialogUnavailable: "当前环境无法打开保存对话框。",
  saveDialogNoPath: "保存对话框未返回文件路径。",
  saveDialogUnsupported: "当前环境不支持文件保存对话框。",
  missingIOUtilsGetChildren: "当前 Zotero 环境缺少 IOUtils.getChildren，无法扫描插件数据目录。",
  missingIOUtils: "当前 Zotero 环境缺少 IOUtils，无法访问论文文件。",
  pathSegmentParent: "路径片段不能包含 ..",

  unsafeRepoPath: "仓库路径不符合 git4zotero 安全路径格式。",
  repoAlreadyMissing: "仓库目录已不存在。",
  metadataMismatchCleanup: "版本元数据与删除事件不匹配，已跳过清理。",

  currentAttachment: "当前附件",
  currentFileMissing: "当前论文文件不存在。",
  metadataFile: "版本元数据",
  metadataRecordCount: "schema {schema}，{count} 条记录。",
  metadataVersionsInvalid: "versions.json 中的 versions 不是数组。",
  metadataVersions: "元数据版本",
  metadataWillUpgrade: "当前 schema {current}，写入后会升级为 {next}。",
  gitRepository: "Git 仓库",
  repositoryInitialized: "已初始化。",
  repositoryGitDirMissing: "尚未找到 .git 目录。",
  historyFilePath: "历史文件路径",
  invalidTrackedVersions: "{count} 条版本缺少可恢复的 tracked 文件路径。",
  currentTrackedFile: "当前 tracked 文件",
  trackedFileMissing: "当前工作树中未找到 tracked 文件；历史版本仍可能可从 Git 恢复。",
  versionHistoryHealth: "版本历史",
  versionHistoryHealthDetail: "面板可读版本 {visibleCount} 条，元数据记录 {metadataCount} 条。",

  exportTitleHistory: "版本历史",
  exportTitleLastCheck: "最近检查差异",
  exportFieldFile: "文件",
  exportFieldItem: "条目",
  exportFieldExportedAt: "导出时间",
  exportFieldTime: "时间",
  exportFieldSize: "大小",
  exportFieldType: "类型",
  exportFieldSummary: "摘要",
  exportNoVersions: "尚未创建版本。",
  exportRecentCheck: "最近检查",
  exportLocationSummary: "位置摘要",
  exportUnknownSize: "大小未知",
  yes: "是",
  no: "否",
  unknown: "unknown",

  restoreSafetyCreated: "恢复前已自动备份：{hash}",
  restoreSafetySkipped: "恢复前自动备份：未创建（设置未启用）",
  restoreTargetVersion: "目标版本",
  restoreFile: "文件",
  backupPathLabel: "备份路径",
  restoreCannotRestore: "无法恢复所选版本：{reason}",
  fileDoesNotExist: "论文文件不存在：{path}",
  missingRestorePath: "历史版本缺少可恢复文件路径，无法恢复。",
  restoreSourceMissing: "无法恢复所选版本：历史版本文件不存在：{path}",
  restoreStagingHashMismatch: "历史版本暂存校验失败，已取消恢复。",
  restoreFailedWithBackupPath: "{message} 备份路径：{path}。{reason}",
  archiveExportTitle: "导出全部版本历史",
  archiveImportTitle: "导入版本历史",
  archiveExportSuccess: "版本历史已导出：{path}\n包含 {repoCount} 个仓库，{fileCount} 个文件。",
  archiveImportSuccess: "版本历史导入完成：导入 {importedCount} 个，跳过 {skippedCount} 个，失败 {failedCount} 个。",
  archiveImportSkippedExisting: "目标仓库已存在，未覆盖。",
  archiveInvalidZip: "备份包不是可识别的 git4zotero ZIP 文件。",
  archiveInvalidEntry: "备份包包含不安全或不支持的路径：{name}",
  archiveNoRepositories: "备份包中未找到可导入的版本仓库。",
  archiveExportDirectoryUnavailable: "迁移导出目录不可用：{path}",
  archiveExportDirectoryNotFolder: "迁移导出路径不是文件夹：{path}",

  preferences: {
    gitSettingsTitle: "Git 设置",
    gitSettingsDescription: "git4zotero 使用本机 Git 在 Zotero 配置目录中保存论文附件版本。",
    gitPathLabel: "Git 可执行文件路径",
    testGit: "测试 Git",
    gitPathHelp: "留空表示使用系统 PATH 中的 git。Windows 可填写 C:\\Program Files\\Git\\cmd\\git.exe。",
    currentInput: "当前输入",
    savedPath: "已保存路径",
    notSaved: "尚未保存",
    gitStatusInitial: "尚未测试 Git。",
    versionBehaviorTitle: "版本行为",
    defaultNoteLabel: "默认版本说明",
    defaultNoteHelp: "创建版本时说明为空，将使用该默认文本。",
    autoSafetyLabel: "恢复旧版本前自动创建安全版本",
    autoSafetyHelp: "建议保持开启，恢复前会先保存当前文件，降低误覆盖风险。",
    statusTitle: "状态与排错",
    pluginVersion: "插件版本",
    supportedFormats: "支持格式",
    supportedFormatsValue: ".docx 正文级识别；.doc 文件级跟踪",
    dataDirectory: "数据目录",
    dataDirectoryFallback: "Zotero 配置目录中的 git4zotero 文件夹",
    trackingHelp: "是否跟踪某个条目由条目列表右键菜单中的“论文版本”操作控制；右侧面板仅显示状态。",
    diagnosticsTitle: "诊断与健康检查",
    diagnosticsDescription: "复制诊断信息可用于提交 issue；健康检查只读取状态，不会自动修复或清理历史。",
    firstUseTitle: "首次使用向导",
    firstUseDescription: "适合第一次安装插件或第一次在新电脑上使用。向导只显示说明和检查结果，不会修改论文文件。",
    openFirstUseGuide: "打开首次使用向导",
    firstUseGuideTitle: "git4zotero 首次使用向导",
    firstUseGuideBody: "1. 安装并测试 Git：本插件只用 Git 在本机保存版本历史，不要求你会写代码。\n2. 数据目录：版本历史保存在 Zotero 配置目录下的 git4zotero 文件夹，不上传云端。\n3. 启用版本管理：在 Zotero 条目列表中右键论文条目或附件，选择“论文版本 → 启用版本管理”。\n4. 保存后创建版本：先在 Word/WPS/LibreOffice 中保存论文，再右键选择“检查修改”和“创建版本...”。\n5. 格式差异：.docx 支持正文级差异；.doc 只能做文件级跟踪。",
    firstUseGuideSubtitle: "按步骤检查必要环境，并可直接执行安全配置和诊断操作。",
    guideClose: "关闭",
    guidePrevious: "上一步",
    guideNext: "下一步",
    guideFinish: "完成",
    guideStatusOk: "正常",
    guideStatusWarning: "需处理",
    guideStatusError: "错误",
    guideStatusPending: "待检查",
    guideStatusChecking: "检查中",
    guideGitStepTitle: "Git 准备",
    guideGitStepDescription: "确认 Git 可执行文件路径和可用状态。git4zotero 只使用本机 Git 保存版本历史。",
    guideGitChecking: "正在检测 Git：{path}",
    guideGitReady: "Git 可用：{detail}\n当前 Git 路径：{path}",
    guideGitMissing: "Git 暂不可用：{detail}\n当前 Git 路径：{path}",
    guideDataStepTitle: "数据目录",
    guideDataStepDescription: "确认插件数据目录位置和写入权限。版本历史保存在这里，不改变 Zotero 原始附件。",
    guideDataReady: "插件数据目录：{path}",
    guideDataFailed: "无法读取插件数据目录：{message}",
    guideDataWriteChecking: "正在检查数据目录写权限...",
    guideDataWriteReady: "写权限正常：{path}",
    guideDataWriteFailed: "写权限检查失败：{message}",
    guideDataActionCheckWrite: "检查写权限",
    guideArchiveStepTitle: "迁移备份",
    guideArchiveStepDescription: "配置“导出全部版本历史...”的默认目录；这不影响导入位置、Zotero 原始附件或插件数据目录。",
    guideArchiveReady: "迁移导出目录：{path}",
    guideArchiveUnset: "未指定迁移导出目录；导出时将使用系统保存对话框默认位置。",
    guideArchiveUnavailable: "迁移导出目录不可用：{message}",
    guideArchiveActionChoose: "选择目录",
    guideItemStepTitle: "论文条目",
    guideItemStepDescription: "检查当前 Zotero 选择是否为单个含 .docx/.doc 附件的条目。向导只检测状态，不启用或创建版本。",
    guideItemNoSelection: "当前未选择条目。请在 Zotero 条目列表中选择一个论文条目或附件。",
    guideItemMultiSelection: "当前选择了 {count} 个条目。请只选择一个条目或附件。",
    guideItemNoAttachment: "当前选择未找到可管理的 .docx/.doc 附件。",
    guideItemReady: "当前选择可管理：{fileName}",
    guideItemActionRefresh: "刷新当前选择状态",
    guideTroubleshootingStepTitle: "排错准备",
    guideTroubleshootingStepDescription: "生成健康检查和诊断信息，方便定位 Git、数据目录和版本仓库问题。",
    guideTroubleshootingReady: "可运行健康检查，或复制脱敏诊断信息和 issue 模板。",
    guideTroubleshootingHealthReady: "健康检查状态：\n{summary}",
    guideActionFailed: "操作失败：{message}",
    lowRiskActionsTitle: "低风险工具",
    openDataDirectory: "打开数据目录",
    copyIssueTemplate: "复制 issue 模板",
    openGitGuide: "打开 Git 安装指南",
    dataDirectoryOpened: "已打开数据目录：{path}",
    dataDirectoryOpenFailed: "无法打开数据目录：{message}",
    issueTemplateCopied: "issue 模板已复制到剪贴板。",
    issueTemplateFallback: "无法写入剪贴板，请手动复制下方 issue 模板：\n{template}",
    gitGuideOpened: "已打开 Git 安装指南。",
    gitGuideOpenFailed: "无法打开 Git 安装指南：{message}",
    archiveActionsTitle: "版本历史备份与迁移",
    archiveActionsDescription: "导出/导入只处理 git4zotero 保存的本地版本历史，不包含 Zotero 原始附件文件。导入时只合并缺失仓库，不覆盖已有历史。",
    archiveExportDirectoryLabel: "迁移导出目录",
    archiveExportDirectoryHelp: "只影响“导出全部版本历史”的默认保存位置；不影响导入位置，也不改变 Zotero 原始附件或插件数据目录。",
    archiveExportDirectoryPlaceholder: "未指定，使用系统保存对话框默认位置",
    archiveExportDirectoryCurrent: "当前迁移导出目录",
    archiveExportDirectoryChoose: "选择目录...",
    archiveExportDirectoryClear: "清空",
    archiveExportDirectoryChooseTitle: "选择迁移导出目录",
    archiveExportDirectorySaved: "迁移导出目录已保存：{path}",
    archiveExportDirectoryCleared: "已清空迁移导出目录，将使用系统保存对话框默认位置。",
    exportAllHistory: "导出全部版本历史...",
    importHistory: "导入版本历史...",
    archiveStatusInitial: "尚未导入或导出版本历史。",
    archiveExporting: "正在导出全部版本历史...",
    archiveImporting: "正在导入版本历史...",
    archiveCanceled: "已取消操作。",
    archiveExportFailed: "导出版本历史失败：{message}",
    archiveImportFailed: "导入版本历史失败：{message}",
    copyDiagnostics: "复制诊断信息",
    runHealthCheck: "运行健康检查",
    diagnosticsInitial: "尚未复制诊断信息。",
    diagnosticsBuilding: "正在生成诊断信息...",
    diagnosticsCopied: "诊断信息已复制到剪贴板。",
    diagnosticsCopyFallback: "无法写入剪贴板，请手动复制下方诊断信息：\n{report}",
    diagnosticsFailed: "诊断信息生成失败：{message}",
    healthInitial: "尚未运行健康检查。",
    healthRunning: "正在运行健康检查...",
    healthFailed: "健康检查失败：{message}",
    healthSummary: "健康检查完成：正常 {okCount} 项，需要处理 {warningCount} 项，错误 {errorCount} 项，跳过 {skippedCount} 项。\n{details}",
    lastErrorTitle: "最近错误",
    lastErrorNone: "尚未记录错误。",
    lastErrorSummary: "{time} · {category} · {operation}\n{message}\n建议：{suggestion}",
    healthStatusOk: "正常",
    healthStatusWarning: "需要处理",
    healthStatusError: "错误",
    healthStatusSkipped: "跳过",
    healthCheckGit: "测试 Git",
    healthCheckDataDirectory: "检查数据目录",
    healthCheckWritePermission: "检查写权限",
    healthCheckDeletedHistory: "扫描已删除条目历史",
    healthCheckMetadataSchema: "检查 metadata schema",
    healthCheckRepositoryConsistency: "检查 Git/index/metadata 一致性",
    healthGitAvailable: "Git 可用：{detail}",
    healthGitUnavailable: "Git 不可用：{detail}",
    healthDataDirectoryReady: "数据目录可用：{path}",
    healthDataDirectoryFailed: "数据目录不可用：{message}",
    healthWritePermissionReady: "写权限正常：{path}",
    healthWritePermissionFailed: "写权限检查失败：{message}",
    healthDeletedHistoryNone: "未发现已删除条目留下的版本历史。",
    healthDeletedHistoryFound: "发现 {count} 个已删除条目留下的版本历史。",
    healthMetadataSchemaOk: "metadata schema 正常，已检查 {count} 个仓库。",
    healthMetadataSchemaIssues: "发现 {count} 个 metadata 问题：{details}",
    healthMetadataSchemaSkipped: "数据目录不存在，已跳过 metadata schema 检查。",
    healthRepositoryConsistencyOk: "Git/index/metadata 一致性正常，已检查 {count} 个仓库。",
    healthRepositoryConsistencyIssues: "发现 {count} 个一致性问题：{details}",
    healthRepositoryConsistencySkipped: "数据目录不存在，已跳过一致性检查。",
    healthSuggestionGit: "建议安装 Git，或在设置页填写正确的 git.exe 路径后重新测试。",
    healthSuggestionDataDirectory: "建议检查 Zotero profile 是否可写，或复制诊断信息提交 issue。",
    healthSuggestionWritePermission: "建议关闭可能占用目录的安全软件或同步软件，确认 Zotero profile 可写后重试。",
    healthSuggestionDeletedHistory: "确认条目已不需要恢复后，可使用“清理已删除条目的历史”显式清理。",
    healthSuggestionMetadata: "建议先不要手动修改仓库文件，复制诊断信息并提交 issue。",
    healthSuggestionConsistency: "建议先不要手动修复仓库；复制诊断信息提交 issue，后续可按明确修复入口处理。",
    checkDeletedHistory: "检查已删除条目的历史",
    cleanDeletedHistory: "清理已删除条目的历史",
    orphanInitial: "尚未检查是否有已删除条目留下的版本历史。",
    orphanHelp: "条目移入 Zotero 回收站时，版本历史会保留，方便恢复条目后继续使用。若条目已被永久删除或清空回收站，插件会清理对应历史；此工具可检查并清理升级前遗留的无对应条目的历史。",
    testingGit: "正在测试 Git...",
    gitAvailable: "Git 可用：{detail}\n已测试路径：{testedPath}\n已保存路径：{savedPath}",
    gitUnavailable: "Git 不可用：{detail}",
    gitPathCheckHint: "请检查 Git 路径。",
    gitTestFailed: "Git 测试失败：{message}",
    orphanChecking: "正在检查是否有已删除条目留下的版本历史...",
    orphanCheckFailed: "已删除条目的历史检查失败：{message}",
    orphanNone: "未发现需要清理的历史。",
    orphanNoneSkipped: "未发现需要清理的历史。{count} 个仓库因路径或元数据异常被跳过。",
    orphanFound: "发现 {count} 个已删除条目留下的版本历史：\n{paths}{more}\n确认这些条目不再需要恢复后，可点击“清理已删除条目的历史”。",
    orphanMore: "\n...另有 {count} 个。",
    orphanCleanTitle: "清理已删除条目的历史",
    orphanCleanConfirm: "将删除 {count} 个 Zotero 中已找不到对应条目的 git4zotero 版本历史。此操作只删除插件保存的历史，不会修改 Zotero 数据库，也不会删除当前论文附件。确定继续吗？",
    orphanCleanCanceled: "已取消清理已删除条目的历史。",
    orphanCleaning: "正在清理已删除条目的历史...",
    orphanCleanFailed: "已删除条目的历史清理失败：{message}",
    orphanCleanSkipped: "已清理 {cleanedCount} 个历史，{skippedCount} 个因安全校验未通过而跳过。",
    orphanCleaned: "已清理 {count} 个已删除条目的版本历史。"
  }
};
