export const PLUGIN_ID = "git4zotero@paper-version.local";
export const PLUGIN_NAME = "git4zotero";
export const FTL_FILE = "git4zotero.ftl";
export const STYLE_ID = "git4zotero-style";
export const SECTION_ID = "git4zotero-paper-versions";
export const ICON_16 = "chrome/content/icons/paper-version-16.png";
export const ICON_20 = "chrome/content/icons/paper-version-20.png";
export const PREFERENCES_XHTML = "chrome/content/preferences.xhtml";
export const PREFERENCES_SCRIPT = "chrome/content/preferences.mjs";
export const PREFERENCES_STYLE = "chrome/content/preferences.css";
export const SUPPORTED_EXTENSIONS = [".docx", ".doc"];

export const PREFS = Object.freeze({
  gitPath: "extensions.git4zotero.gitPath",
  defaultVersionNote: "extensions.git4zotero.defaultVersionNote",
  autoSafetyVersion: "extensions.git4zotero.autoSafetyVersion"
});

export const UI_TEXT = {
  locale: "zh-CN",
  dateLocale: "zh-CN",
  colon: "：",
  semicolon: "；",
  listComma: "，",
  fullStop: "。",
  menuRoot: "论文版本",
  preferencePaneLabel: "Git",
  loading: "正在读取论文版本信息…",
  noItem: "请选择一个 Zotero 条目。",
  gitUnavailable: "Git 不可用",
  gitUnavailableDetail: "未检测到可用的 Git。请安装 Git，或配置 Git 可执行文件路径。",
  gitPathNotFound: "未找到 Git 可执行文件。请在“论文版本管理”设置中填写完整 git.exe 路径，例如 C:\\Program Files\\Git\\cmd\\git.exe。",
  gitPathActionRequired: "未找到 Git 可执行文件，请填写完整 git.exe 路径",
  gitConfigured: "Git 路径已配置",
  configureGit: "配置 Git 路径",
  refreshPanel: "刷新",
  refreshingPanel: "正在刷新…",
  noDocument: "未找到可管理的论文文件",
  noDocumentDetail: "请为当前条目添加 .docx 或 .doc 附件。",
  rightClickHint: "请在条目列表中右键条目或论文附件进行版本操作。",
  notEnabled: "尚未启用版本管理",
  notEnabledDetail: "只有通过右键菜单启用的条目才会被 git4zotero 跟踪。未启用条目不会创建 Git 仓库，也不会保存或恢复版本。",
  enableManagement: "启用版本管理",
  enablingManagement: "正在启用版本管理…",
  enableSuccess: "已为当前条目启用论文版本管理。",
  disableManagement: "停用版本管理",
  disablingManagement: "正在停用版本管理…",
  disableConfirmTitle: "停用版本管理",
  disableConfirmMessage: "停用后不会删除已有版本历史，但当前条目将不再允许检查、创建或恢复版本。确定继续吗？",
  disableSuccess: "已停用当前条目的论文版本管理。",
  itemNotEnabledError: "当前条目尚未启用论文版本管理。",
  currentFile: "当前论文文件",
  createVersion: "创建版本",
  creatingVersion: "正在创建版本…",
  checkChanges: "检查修改",
  checkingChanges: "正在检查修改…",
  lastCheck: "最近检查",
  neverChecked: "尚未检查修改。",
  workingTree: "Git 工作树",
  workingTreeClean: "工作树无未提交修改。",
  workingTreeUninitialized: "尚未创建 Git 仓库。",
  versionHistory: "版本历史",
  restoreVersion: "恢复此版本",
  restoringVersion: "正在恢复版本…",
  emptyHistory: "尚未创建版本。",
  notePlaceholder: "输入本次版本说明，例如：完成引言修改",
  defaultNote: "论文版本",
  safetyNotePrefix: "恢复前自动备份",
  restoreConfirmTitle: "恢复论文版本",
  restoreConfirmMessage: "恢复会先自动备份当前文件，然后用所选版本覆盖当前论文附件。确定继续吗？",
  createSuccess: "版本已创建。",
  noChangesToSave: "未检测到修改，无需创建新版本。",
  restoreSuccess: "版本已恢复。",
  restoreSafetyBackup: "恢复前当前文件备份",
  restorePreflightMissing: "当前论文文件不存在，无法恢复。",
  restorePreflightUnreadable: "当前论文文件不可读取，无法安全恢复。",
  restorePreflightUnwritable: "当前论文文件所在目录不可写，无法安全恢复。",
  restoreFailedWithBackup: "恢复失败，当前文件已保留备份。",
  restoreHashMismatch: "恢复后的文件校验失败，已尝试回滚到恢复前状态。",
  repositoryHealth: "仓库健康",
  repositoryHealthOk: "版本仓库状态正常。",
  repositoryHealthWarning: "版本仓库存在需要关注的问题。",
  repositoryHealthError: "版本仓库存在影响恢复的问题。",
  operationFailed: "操作失败",
  actionCompleted: "操作完成。",
  menuUnavailable: "论文版本操作不可用",
  menuMultiSelectUnsupported: "请只选择一个 Zotero 条目或论文附件。",
  menuCreatePromptTitle: "创建论文版本",
  menuCreatePromptMessage: "请输入本次版本说明。",
  menuRestorePromptTitle: "恢复论文版本",
  menuRestorePromptMessage: "请选择要恢复的版本。",
  menuExportSummary: "导出版本摘要",
  menuExportSummaryLabel: "导出版本摘要...",
  menuExportScopeMessage: "请选择要导出的内容。",
  menuExportFormatMessage: "请选择导出格式。",
  exportScopeHistory: "完整版本历史",
  exportScopeLastCheck: "最近检查差异",
  exportFormatMarkdown: "Markdown",
  exportFormatText: "纯文本",
  exportSuccess: "版本摘要已导出。",
  exportNoLastCheck: "尚未检查修改，无法导出最近检查差异。",
  menuNoVersions: "当前条目尚未创建版本。",
  menuStatusLoading: "正在读取论文版本状态...",
  menuStatusNoSelection: "请选择一个条目或论文附件。",
  menuStatusReady: "论文版本可用。",
  menuStatusNoHistory: "尚未创建版本。",
  menuDisabledReasonPrefix: "不可用",
  menuConfigureGit: "配置 Git 路径...",
  invalidCommit: "版本标识无效，已取消恢复。",
  promptGitTitle: "配置 Git 路径",
  promptGitMessage: "请输入 Git 可执行文件路径。留空表示使用系统 PATH 中的 git。",
  contentModeDocx: ".docx 正文级识别",
  contentModeFileOnly: "文件级跟踪",
  docFileOnlyTracking: ".doc 仅支持文件级跟踪，可创建和恢复版本，但不解析正文差异。",
  versionDetails: "版本详情",
  savedBeforeCheck: "请先在 Word/WPS/LibreOffice 中保存论文文件，再回到 Zotero 检查修改或创建版本。",

  stateDirty: "有未提交修改",
  stateClean: "工作树干净",
  stateUnchecked: "尚未检查工作树",
  stateEnabled: "已启用",
  stateVersionCount: "{count} 个版本",
  stateLatest: "最新 {value}",
  workflow: "工作流",
  workflowAddAttachmentTitle: "添加论文附件",
  workflowAddAttachmentDetail: "为当前条目添加 .docx 或 .doc 文件后再进行版本管理。",
  workflowEnableTitle: "启用版本管理",
  workflowEnableDetail: "右键条目或附件，选择“{menuRoot} → {enableManagement}”。",
  workflowCheckCreateFirstTitle: "检查修改并创建首个版本",
  workflowCheckCreateFirstCurrentTitle: "检查并创建首个版本",
  workflowCheckCreateFirstDetail: "启用后使用“{checkChanges}”确认差异，再使用“{createVersion}”。",
  workflowEnabledTitle: "版本管理已启用",
  workflowConfigureGitTitle: "配置 Git",
  workflowConfigureGitDetail: "打开设置页填写 Git 路径，或右键选择“{menuConfigureGit}”。",
  workflowCheckCurrentTitle: "检查当前修改",
  workflowCheckSavedDetail: "保存论文文件后，右键选择“{checkChanges}”；确认无误后选择“{createVersion}”。",
  workflowRestoreHistoryTitle: "恢复历史版本",
  workflowRestoreHistoryAvailable: "已有 {count} 个版本，可右键选择“{restoreVersionMenu}”。",
  workflowRestoreHistoryEmpty: "创建首个版本后，这里会显示可恢复的历史。",
  workflowWorkingTreeTitle: "工作树状态",
  workflowWorkingTreeDirty: "检测到未提交修改，创建版本后会进入历史记录。",
  contentSummaryDocx: "正文 {paragraphCount} 段 · {wordCount} 字/词",
  additionalIssues: "另有 {count} 个问题未展开。",
  versionNoteLabel: "版本说明",
  createdAtLabel: "创建时间",
  gitHashLabel: "Git hash",
  fileNameLabel: "文件名",
  fileSizeLabel: "文件大小",
  versionTypeLabel: "版本类型",
  safetyBackupLabel: "安全备份",
  changeSummaryLabel: "变化摘要",
  trackingModeLabel: "跟踪方式",
  safetyBackupYes: "是，恢复前自动备份",
  safetyBackupNo: "否",
  versionKindSafety: "自动备份",
  versionKindGit: "Git 历史",
  versionKindManual: "手动",
  versionKindSafetyFull: "恢复前自动备份",
  versionKindManualFull: "手动版本",
  omittedParagraphChanges: "另有 {count} 处段落变化未展开。",
  omittedParagraphChangesDialog: "另有 {count} 处段落变化未在弹窗中展开。",
  concreteChanges: "具体修改",
  changeBefore: "修改前",
  changeAfter: "修改后",
  changeDeleted: "删除",
  changeAdded: "新增",
  changeKindAdded: "新增段落",
  changeKindDeleted: "删除段落",
  changeKindModified: "修改段落",
  changeKindParagraph: "段落变化",
  paragraphIndex: "第 {index} 段",
  emptyParagraph: "（空段落）",

  sourceDocument: "正文",
  sourceFootnotes: "脚注",
  sourceEndnotes: "尾注",
  sourceHeader: "页眉",
  sourceFooter: "页脚",
  tableLabel: "表格",
  tableWithIndex: "表格 {index}",
  untitledBody: "无标题正文",
  changeCount: "{count} 处变化",

  firstDocxSummary: "首次创建版本，将保存当前 .docx 正文内容快照。",
  noChanges: "未检测到修改。",
  fileOnlyFormattingSummary: "正文内容未变化，仅检测到格式、样式、元数据或 Word 内部状态变化。",
  docxContentChanged: "正文内容已修改",
  addedParagraphs: "新增 {count} 段",
  deletedParagraphs: "删除 {count} 段",
  modifiedParagraphs: "修改 {count} 段",
  wordDelta: "字数变化 {value}",
  firstDocxUnreadableSummary: "首次创建版本，当前 .docx 暂不可解析，已保存文件级快照。",
  firstFileLevelSummary: "首次创建版本，{extension} 将保存文件级快照。",
  thisFormat: "该格式",
  docxReadFailedSummary: "当前 .docx 暂不可解析，已按文件级快照保存；请确认文件已由 Word/WPS 完整保存。",
  genericFileLevelSummary: "当前格式仅支持文件级识别：文件内容已变化，但不解析正文差异。",
  noDocxByteReader: "当前环境无法读取 docx 文件字节。",
  missingDocumentXml: "无法识别 docx 正文：缺少 word/document.xml。",
  noComparableText: "未在 docx 正文、脚注或尾注中识别到可比对文本。请确认文件已保存且包含正文。",
  invalidDocxZipDirectory: "无效的 docx 压缩目录。",
  invalidDocxLocalHeader: "docx 条目 {name} 的本地头无效。",
  unsupportedCompressionMethod: "暂不支持的压缩方式：{method}",
  docxEntryInflateFailed: "无法解析 docx 条目 {name} 的压缩内容：{message}",
  docxEntrySizeMismatch: "docx 条目 {name} 解压长度不符：期望 {expected}，实际 {actual}。",
  missingZipCentralDirectory: "无法读取 docx：未找到 ZIP 中央目录。",
  compressedDataUnexpectedEnd: "压缩数据意外结束。",

  invalidTrackedPath: "跟踪文件路径无效，已取消恢复。",
  gitStatusFailed: "无法读取 Git 工作树状态。",
  gitCommandFailed: "Git 命令失败：git {args}",
  processExitCode: "退出码 {code}",
  saveFileTitle: "保存文件",
  saveDialogUnavailable: "当前环境无法打开保存对话框。",
  saveDialogNoPath: "保存对话框未返回文件路径。",
  saveDialogUnsupported: "当前环境不支持文件保存对话框。",
  missingIOUtilsGetChildren: "当前 Zotero 环境缺少 IOUtils.getChildren，无法扫描插件数据目录。",
  missingIOUtils: "当前 Zotero 环境缺少 IOUtils，无法访问论文文件。",
  pathSegmentParent: "路径片段不能包含 ..",

  unsafeRepoPath: "仓库路径不符合 git4zotero 安全路径格式。",
  repoAlreadyMissing: "仓库目录已不存在。",
  metadataMismatchCleanup: "版本元数据与删除事件不匹配，已跳过清理。",

  currentAttachment: "当前附件",
  currentFileMissing: "当前论文文件不存在。",
  metadataFile: "版本元数据",
  metadataRecordCount: "schema {schema}，{count} 条记录。",
  metadataVersionsInvalid: "versions.json 中的 versions 不是数组。",
  metadataVersions: "元数据版本",
  metadataWillUpgrade: "当前 schema {current}，写入后会升级为 {next}。",
  gitRepository: "Git 仓库",
  repositoryInitialized: "已初始化。",
  repositoryGitDirMissing: "尚未找到 .git 目录。",
  historyFilePath: "历史文件路径",
  invalidTrackedVersions: "{count} 条版本缺少可恢复的 tracked 文件路径。",
  currentTrackedFile: "当前 tracked 文件",
  trackedFileMissing: "当前工作树中未找到 tracked 文件；历史版本仍可能可从 Git 恢复。",
  versionHistoryHealth: "版本历史",
  versionHistoryHealthDetail: "面板可读版本 {visibleCount} 条，元数据记录 {metadataCount} 条。",

  exportTitleHistory: "版本历史",
  exportTitleLastCheck: "最近检查差异",
  exportFieldFile: "文件",
  exportFieldItem: "条目",
  exportFieldExportedAt: "导出时间",
  exportFieldTime: "时间",
  exportFieldSize: "大小",
  exportFieldType: "类型",
  exportFieldSummary: "摘要",
  exportNoVersions: "尚未创建版本。",
  exportRecentCheck: "最近检查",
  exportLocationSummary: "位置摘要",
  exportUnknownSize: "大小未知",
  yes: "是",
  no: "否",
  unknown: "unknown",

  restoreSafetyCreated: "恢复前已自动备份：{hash}",
  restoreSafetySkipped: "恢复前自动备份：未创建（设置未启用）",
  restoreTargetVersion: "目标版本",
  restoreFile: "文件",
  backupPathLabel: "备份路径",
  restoreCannotRestore: "无法恢复所选版本：{reason}",
  fileDoesNotExist: "论文文件不存在：{path}",
  missingRestorePath: "历史版本缺少可恢复文件路径，无法恢复。",
  restoreSourceMissing: "无法恢复所选版本：历史版本文件不存在：{path}",
  restoreStagingHashMismatch: "历史版本暂存校验失败，已取消恢复。",
  restoreFailedWithBackupPath: "{message} 备份路径：{path}。{reason}",

  preferences: {
    gitSettingsTitle: "Git 设置",
    gitSettingsDescription: "git4zotero 使用本机 Git 在 Zotero 配置目录中保存论文附件版本。",
    gitPathLabel: "Git 可执行文件路径",
    testGit: "测试 Git",
    gitPathHelp: "留空表示使用系统 PATH 中的 git。Windows 可填写 C:\\Program Files\\Git\\cmd\\git.exe。",
    currentInput: "当前输入",
    savedPath: "已保存路径",
    notSaved: "尚未保存",
    gitStatusInitial: "尚未测试 Git。",
    versionBehaviorTitle: "版本行为",
    defaultNoteLabel: "默认版本说明",
    defaultNoteHelp: "创建版本时说明为空，将使用该默认文本。",
    autoSafetyLabel: "恢复旧版本前自动创建安全版本",
    autoSafetyHelp: "建议保持开启，恢复前会先保存当前文件，降低误覆盖风险。",
    statusTitle: "状态与排错",
    pluginVersion: "插件版本",
    supportedFormats: "支持格式",
    supportedFormatsValue: ".docx 正文级识别；.doc 文件级跟踪",
    dataDirectory: "数据目录",
    dataDirectoryFallback: "Zotero 配置目录中的 git4zotero 文件夹",
    trackingHelp: "是否跟踪某个条目由条目列表右键菜单中的“论文版本”操作控制；右侧面板仅显示状态。",
    checkDeletedHistory: "检查已删除条目的历史",
    cleanDeletedHistory: "清理已删除条目的历史",
    orphanInitial: "尚未检查是否有已删除条目留下的版本历史。",
    orphanHelp: "条目移入 Zotero 回收站时，版本历史会保留，方便恢复条目后继续使用。若条目已被永久删除或清空回收站，插件会清理对应历史；此工具可检查并清理升级前遗留的无对应条目的历史。",
    testingGit: "正在测试 Git...",
    gitAvailable: "Git 可用：{detail}\n已测试路径：{testedPath}\n已保存路径：{savedPath}",
    gitUnavailable: "Git 不可用：{detail}",
    gitPathCheckHint: "请检查 Git 路径。",
    gitTestFailed: "Git 测试失败：{message}",
    orphanChecking: "正在检查是否有已删除条目留下的版本历史...",
    orphanCheckFailed: "已删除条目的历史检查失败：{message}",
    orphanNone: "未发现需要清理的历史。",
    orphanNoneSkipped: "未发现需要清理的历史。{count} 个仓库因路径或元数据异常被跳过。",
    orphanFound: "发现 {count} 个已删除条目留下的版本历史：\n{paths}{more}\n确认这些条目不再需要恢复后，可点击“清理已删除条目的历史”。",
    orphanMore: "\n...另有 {count} 个。",
    orphanCleanTitle: "清理已删除条目的历史",
    orphanCleanConfirm: "将删除 {count} 个 Zotero 中已找不到对应条目的 git4zotero 版本历史。此操作只删除插件保存的历史，不会修改 Zotero 数据库，也不会删除当前论文附件。确定继续吗？",
    orphanCleanCanceled: "已取消清理已删除条目的历史。",
    orphanCleaning: "正在清理已删除条目的历史...",
    orphanCleanFailed: "已删除条目的历史清理失败：{message}",
    orphanCleanSkipped: "已清理 {cleanedCount} 个历史，{skippedCount} 个因安全校验未通过而跳过。",
    orphanCleaned: "已清理 {count} 个已删除条目的版本历史。"
  }
};
