import { UI_TEXT } from "./constants.mjs";

const ZH_CN_TEXT = cloneText(UI_TEXT);

const UI_TEXT_BUNDLES = Object.freeze({
  "zh-CN": ZH_CN_TEXT,
  "zh-TW": buildBundle({
    locale: "zh-TW",
    dateLocale: "zh-TW",
    colon: "：",
    semicolon: "；",
    listComma: "，",
    fullStop: "。",
    menuRoot: "論文版本",
    loading: "正在讀取論文版本資訊…",
    noItem: "請選擇一個 Zotero 條目。",
    gitUnavailable: "Git 不可用",
    gitUnavailableDetail: "未偵測到可用的 Git。請安裝 Git，或設定 Git 可執行檔路徑。",
    gitPathNotFound: "找不到 Git 可執行檔。請在「論文版本管理」設定中填寫完整 git.exe 路徑，例如 C:\\Program Files\\Git\\cmd\\git.exe。",
    gitPathActionRequired: "找不到 Git 可執行檔，請填寫完整 git.exe 路徑",
    gitConfigured: "Git 路徑已設定",
    configureGit: "設定 Git 路徑",
    refreshPanel: "重新整理",
    refreshingPanel: "正在重新整理…",
    noDocument: "找不到可管理的論文檔案",
    noDocumentDetail: "請為目前條目新增 .docx 或 .doc 附件。",
    rightClickHint: "請在條目清單中右鍵條目或論文附件進行版本操作。",
    notEnabled: "尚未啟用版本管理",
    notEnabledDetail: "只有透過右鍵選單啟用的條目才會被 git4zotero 追蹤。未啟用條目不會建立 Git 倉庫，也不會儲存或還原版本。",
    enableManagement: "啟用版本管理",
    enablingManagement: "正在啟用版本管理…",
    enableSuccess: "已為目前條目啟用論文版本管理。",
    disableManagement: "停用版本管理",
    disablingManagement: "正在停用版本管理…",
    disableConfirmTitle: "停用版本管理",
    disableConfirmMessage: "停用後不會刪除既有版本歷史，但目前條目將不再允許檢查、建立或還原版本。確定繼續嗎？",
    disableSuccess: "已停用目前條目的論文版本管理。",
    itemNotEnabledError: "目前條目尚未啟用論文版本管理。",
    currentFile: "目前論文檔案",
    createVersion: "建立版本",
    creatingVersion: "正在建立版本…",
    checkChanges: "檢查修改",
    checkingChanges: "正在檢查修改…",
    lastCheck: "最近檢查",
    neverChecked: "尚未檢查修改。",
    workingTree: "Git 工作樹",
    workingTreeClean: "工作樹沒有未提交修改。",
    workingTreeUninitialized: "尚未建立 Git 倉庫。",
    versionHistory: "版本歷史",
    restoreVersion: "還原此版本",
    restoringVersion: "正在還原版本…",
    emptyHistory: "尚未建立版本。",
    notePlaceholder: "輸入本次版本說明，例如：完成引言修改",
    defaultNote: "論文版本",
    safetyNotePrefix: "還原前自動備份",
    restoreConfirmTitle: "還原論文版本",
    restoreConfirmMessage: "還原會先自動備份目前檔案，然後用所選版本覆蓋目前論文附件。確定繼續嗎？",
    createSuccess: "版本已建立。",
    noChangesToSave: "未偵測到修改，無需建立新版本。",
    restoreSuccess: "版本已還原。",
    restoreSafetyBackup: "還原前目前檔案備份",
    restorePreflightMissing: "目前論文檔案不存在，無法還原。",
    restorePreflightUnreadable: "目前論文檔案無法讀取，無法安全還原。",
    restorePreflightUnwritable: "目前論文檔案所在目錄不可寫入，無法安全還原。",
    restorePreflightWritable: "目前檔案目錄可寫入",
    restorePreflightBlocked: "還原預檢未通過，已阻止還原。",
    restorePreflightWarning: "還原預檢通過，但存在需要注意的風險。請先儲存並關閉 Word/WPS/LibreOffice 後再繼續。",
    restorePreflightOk: "還原預檢通過。",
    restorePreflightChanged: "確認後目前論文檔案已發生變化，已取消還原。請重新執行還原操作。",
    restoreTargetHash: "目標版本檔案 hash",
    restoreTargetHashUnknown: "此歷史版本未記錄檔案 hash；還原時仍會校驗實際 Git 檔案。",
    restorePreflightTitle: "還原前安全檢查",
    restorePreflightConfirmIntro: "請確認以下還原資訊。若檔案仍在 Word/WPS/LibreOffice 中開啟，請先儲存並關閉後再繼續。",
    restorePreflightErrors: "發現 {count} 個阻止還原的問題。",
    restorePreflightWarnings: "發現 {count} 個需要注意的問題。",
    restorePreflightProceed: "繼續還原會先備份目前檔案，再替換為目標版本。確定繼續嗎？",
    restoreFailedWithBackup: "還原失敗，目前檔案已保留備份。",
    restoreHashMismatch: "還原後的檔案校驗失敗，已嘗試回復到還原前狀態。",
    repositoryHealth: "倉庫健康",
    repositoryHealthOk: "版本倉庫狀態正常。",
    repositoryHealthWarning: "版本倉庫存在需要注意的問題。",
    repositoryHealthError: "版本倉庫存在影響還原的問題。",
    operationFailed: "操作失敗",
    errorUserActionableTitle: "需要使用者處理",
    errorGitTitle: "Git 問題",
    errorFileStateTitle: "檔案狀態問題",
    errorInternalTitle: "插件內部錯誤",
    errorUserActionableSuggestion: "請依提示完成選擇、啟用版本管理，或先檢查修改後再操作。",
    errorGitSuggestion: "請確認 Git 已安裝，並在設定頁填寫正確的 Git 可執行檔路徑後重新測試。",
    errorFileStateSuggestion: "請確認論文檔案存在、已儲存，且未被 Word/WPS/LibreOffice 占用。",
    errorInternalSuggestion: "請複製診斷資訊並在 issue 中附上操作步驟，便於定位問題。",
    actionCompleted: "操作完成。",
    menuUnavailable: "論文版本操作不可用",
    menuMultiSelectUnsupported: "請只選擇一個 Zotero 條目或論文附件。",
    menuCreatePromptTitle: "建立論文版本",
    menuCreatePromptMessage: "請輸入本次版本說明。",
    createPreviewTitle: "建立版本前確認",
    createPreviewConfirmMessage: "請確認本次將儲存的版本資訊。",
    createPreviewProceed: "確定建立這個版本嗎？",
    createPreviewNoChanges: "未偵測到可儲存的變化。",
    createPreviewDocWarning: ".doc 僅做檔案級追蹤，本次版本不會產生正文級差異。",
    menuRestorePromptTitle: "還原論文版本",
    menuRestorePromptMessage: "請選擇要還原的版本。",
    menuExportSummary: "匯出版本摘要",
    menuExportSummaryLabel: "匯出版本摘要...",
    menuExportScopeMessage: "請選擇要匯出的內容。",
    menuExportFormatMessage: "請選擇匯出格式。",
    exportScopeHistory: "完整版本歷史",
    exportScopeLastCheck: "最近檢查差異",
    exportFormatText: "純文字",
    exportSuccess: "版本摘要已匯出。",
    exportNoLastCheck: "尚未檢查修改，無法匯出最近檢查差異。",
    menuNoVersions: "目前條目尚未建立版本。",
    menuStatusLoading: "正在讀取論文版本狀態...",
    menuStatusNoSelection: "請選擇一個條目或論文附件。",
    menuStatusReady: "論文版本可用。",
    menuStatusNoHistory: "尚未建立版本。",
    menuDisabledReasonPrefix: "不可用",
    menuConfigureGit: "設定 Git 路徑...",
    invalidCommit: "版本識別碼無效，已取消還原。",
    promptGitTitle: "設定 Git 路徑",
    promptGitMessage: "請輸入 Git 可執行檔路徑。留空表示使用系統 PATH 中的 git。",
    contentModeDocx: ".docx 正文級識別",
    contentModeFileOnly: "檔案級追蹤",
    docFileOnlyTracking: ".doc 僅支援檔案級追蹤，可建立和還原版本，但不解析正文差異。",
    versionDetails: "版本詳情",
    savedBeforeCheck: "請先在 Word/WPS/LibreOffice 中儲存論文檔案，再回到 Zotero 檢查修改或建立版本。",
    stateDirty: "有未提交修改",
    stateClean: "工作樹乾淨",
    stateUnchecked: "尚未檢查工作樹",
    stateEnabled: "已啟用",
    stateDisabled: "未啟用",
    stateGitAvailable: "Git 可用",
    stateGitUnavailable: "Git 不可用",
    stateLatestVersion: "最近版本",
    stateLastCheck: "最近檢查",
    stateWorkingTree: "未提交修改",
    statusCardsTitle: "目前狀態",
    stateVersionCount: "{count} 個版本",
    stateLatest: "最新 {value}",
    workflow: "工作流",
    workflowAddAttachmentTitle: "新增論文附件",
    workflowAddAttachmentDetail: "為目前條目新增 .docx 或 .doc 檔案後再進行版本管理。",
    workflowEnableTitle: "啟用版本管理",
    workflowEnableDetail: "右鍵條目或附件，選擇「{menuRoot} → {enableManagement}」。",
    workflowCheckCreateFirstTitle: "檢查修改並建立首個版本",
    workflowCheckCreateFirstCurrentTitle: "檢查並建立首個版本",
    workflowCheckCreateFirstDetail: "啟用後使用「{checkChanges}」確認差異，再使用「{createVersion}」。",
    workflowEnabledTitle: "版本管理已啟用",
    workflowConfigureGitTitle: "設定 Git",
    workflowConfigureGitDetail: "開啟設定頁填寫 Git 路徑，或右鍵選擇「{menuConfigureGit}」。",
    workflowCheckCurrentTitle: "檢查目前修改",
    workflowCheckSavedDetail: "儲存論文檔案後，右鍵選擇「{checkChanges}」；確認無誤後選擇「{createVersion}」。",
    workflowRestoreHistoryTitle: "還原歷史版本",
    workflowRestoreHistoryAvailable: "已有 {count} 個版本，可右鍵選擇「{restoreVersionMenu}」。",
    workflowRestoreHistoryEmpty: "建立首個版本後，這裡會顯示可還原的歷史。",
    workflowWorkingTreeTitle: "工作樹狀態",
    workflowWorkingTreeDirty: "偵測到未提交修改，建立版本後會進入歷史記錄。",
    contentSummaryDocx: "正文 {paragraphCount} 段 · {wordCount} 字/詞",
    additionalIssues: "另有 {count} 個問題未展開。",
    versionNoteLabel: "版本說明",
    createdAtLabel: "建立時間",
    fileNameLabel: "檔案名稱",
    fileSizeLabel: "檔案大小",
    versionTypeLabel: "版本類型",
    safetyBackupLabel: "安全備份",
    changeSummaryLabel: "變更摘要",
    trackingModeLabel: "追蹤方式",
    safetyBackupYes: "是，還原前自動備份",
    safetyBackupNo: "否",
    versionKindSafety: "自動備份",
    versionKindGit: "Git 歷史",
    versionKindManual: "手動",
    versionKindSafetyFull: "還原前自動備份",
    versionKindManualFull: "手動版本",
    omittedParagraphChanges: "另有 {count} 處段落變化未展開。",
    omittedParagraphChangesDialog: "另有 {count} 處段落變化未在彈窗中展開。",
    concreteChanges: "具體修改",
    changeBefore: "修改前",
    changeAfter: "修改後",
    changeDeleted: "刪除",
    changeAdded: "新增",
    changeKindAdded: "新增段落",
    changeKindDeleted: "刪除段落",
    changeKindModified: "修改段落",
    changeKindParagraph: "段落變化",
    paragraphIndex: "第 {index} 段",
    emptyParagraph: "（空段落）",
    sourceDocument: "正文",
    sourceFootnotes: "註腳",
    sourceEndnotes: "尾註",
    sourceHeader: "頁首",
    sourceFooter: "頁尾",
    tableLabel: "表格",
    tableWithIndex: "表格 {index}",
    untitledBody: "無標題正文",
    changeCount: "{count} 處變化",
    firstDocxSummary: "首次建立版本，將儲存目前 .docx 正文內容快照。",
    noChanges: "未偵測到修改。",
    fileOnlyFormattingSummary: "正文內容未變化，僅偵測到格式、樣式、元資料或 Word 內部狀態變化。",
    docxContentChanged: "正文內容已修改",
    addedParagraphs: "新增 {count} 段",
    deletedParagraphs: "刪除 {count} 段",
    modifiedParagraphs: "修改 {count} 段",
    wordDelta: "字數變化 {value}",
    firstDocxUnreadableSummary: "首次建立版本，目前 .docx 暫不可解析，已儲存檔案級快照。",
    firstFileLevelSummary: "首次建立版本，{extension} 將儲存檔案級快照。",
    thisFormat: "此格式",
    docxReadFailedSummary: "目前 .docx 暫不可解析，已按檔案級快照儲存；請確認檔案已由 Word/WPS 完整儲存。",
    genericFileLevelSummary: "目前格式僅支援檔案級識別：檔案內容已變化，但不解析正文差異。",
    noDocxByteReader: "目前環境無法讀取 docx 檔案位元組。",
    missingDocumentXml: "無法識別 docx 正文：缺少 word/document.xml。",
    noComparableText: "未在 docx 正文、註腳或尾註中識別到可比對文字。請確認檔案已儲存且包含正文。",
    invalidDocxZipDirectory: "無效的 docx 壓縮目錄。",
    invalidDocxLocalHeader: "docx 條目 {name} 的本地標頭無效。",
    unsupportedCompressionMethod: "暫不支援的壓縮方式：{method}",
    docxEntryInflateFailed: "無法解析 docx 條目 {name} 的壓縮內容：{message}",
    docxEntrySizeMismatch: "docx 條目 {name} 解壓長度不符：期望 {expected}，實際 {actual}。",
    missingZipCentralDirectory: "無法讀取 docx：未找到 ZIP 中央目錄。",
    compressedDataUnexpectedEnd: "壓縮資料意外結束。",
    invalidTrackedPath: "追蹤檔案路徑無效，已取消還原。",
    gitStatusFailed: "無法讀取 Git 工作樹狀態。",
    gitCommandFailed: "Git 命令失敗：git {args}",
    processExitCode: "退出碼 {code}",
    saveFileTitle: "儲存檔案",
    saveDialogUnavailable: "目前環境無法開啟儲存對話框。",
    saveDialogNoPath: "儲存對話框未回傳檔案路徑。",
    saveDialogUnsupported: "目前環境不支援檔案儲存對話框。",
    missingIOUtilsGetChildren: "目前 Zotero 環境缺少 IOUtils.getChildren，無法掃描插件資料目錄。",
    missingIOUtils: "目前 Zotero 環境缺少 IOUtils，無法存取論文檔案。",
    pathSegmentParent: "路徑片段不能包含 ..",
    unsafeRepoPath: "倉庫路徑不符合 git4zotero 安全路徑格式。",
    repoAlreadyMissing: "倉庫目錄已不存在。",
    metadataMismatchCleanup: "版本元資料與刪除事件不匹配，已跳過清理。",
    currentAttachment: "目前附件",
    currentFileMissing: "目前論文檔案不存在。",
    metadataFile: "版本元資料",
    metadataRecordCount: "schema {schema}，{count} 條記錄。",
    metadataVersionsInvalid: "versions.json 中的 versions 不是陣列。",
    metadataVersions: "元資料版本",
    metadataWillUpgrade: "目前 schema {current}，寫入後會升級為 {next}。",
    gitRepository: "Git 倉庫",
    repositoryInitialized: "已初始化。",
    repositoryGitDirMissing: "尚未找到 .git 目錄。",
    historyFilePath: "歷史檔案路徑",
    invalidTrackedVersions: "{count} 條版本缺少可還原的 tracked 檔案路徑。",
    currentTrackedFile: "目前 tracked 檔案",
    trackedFileMissing: "目前工作樹中未找到 tracked 檔案；歷史版本仍可能可從 Git 還原。",
    versionHistoryHealth: "版本歷史",
    versionHistoryHealthDetail: "面板可讀版本 {visibleCount} 條，元資料記錄 {metadataCount} 條。",
    exportTitleHistory: "版本歷史",
    exportTitleLastCheck: "最近檢查差異",
    exportFieldFile: "檔案",
    exportFieldItem: "條目",
    exportFieldExportedAt: "匯出時間",
    exportFieldTime: "時間",
    exportFieldSize: "大小",
    exportFieldType: "類型",
    exportFieldSummary: "摘要",
    exportNoVersions: "尚未建立版本。",
    exportRecentCheck: "最近檢查",
    exportLocationSummary: "位置摘要",
    exportUnknownSize: "大小未知",
    yes: "是",
    no: "否",
    restoreSafetyCreated: "還原前已自動備份：{hash}",
    restoreSafetySkipped: "還原前自動備份：未建立（設定未啟用）",
    restoreTargetVersion: "目標版本",
    restoreFile: "檔案",
    backupPathLabel: "備份路徑",
    restoreCannotRestore: "無法還原所選版本：{reason}",
    fileDoesNotExist: "論文檔案不存在：{path}",
    missingRestorePath: "歷史版本缺少可還原檔案路徑，無法還原。",
    restoreSourceMissing: "無法還原所選版本：歷史版本檔案不存在：{path}",
    restoreStagingHashMismatch: "歷史版本暫存校驗失敗，已取消還原。",
    restoreFailedWithBackupPath: "{message} 備份路徑：{path}。{reason}",
    archiveExportTitle: "匯出全部版本歷史",
    archiveImportTitle: "匯入版本歷史",
    archiveExportSuccess: "版本歷史已匯出：{path}\n包含 {repoCount} 個倉庫，{fileCount} 個檔案。",
    archiveImportSuccess: "版本歷史匯入完成：匯入 {importedCount} 個，跳過 {skippedCount} 個，失敗 {failedCount} 個。",
    archiveImportSkippedExisting: "目標倉庫已存在，未覆蓋。",
    archiveInvalidZip: "備份包不是可識別的 git4zotero ZIP 檔案。",
    archiveInvalidEntry: "備份包包含不安全或不支援的路徑：{name}",
    archiveNoRepositories: "備份包中找不到可匯入的版本倉庫。",
    archiveExportDirectoryUnavailable: "遷移匯出目錄不可用：{path}",
    archiveExportDirectoryNotFolder: "遷移匯出路徑不是資料夾：{path}",
    preferences: {
      gitSettingsTitle: "Git 設定",
      gitSettingsDescription: "git4zotero 使用本機 Git 在 Zotero 設定目錄中儲存論文附件版本。",
      gitPathLabel: "Git 可執行檔路徑",
      testGit: "測試 Git",
      gitPathHelp: "留空表示使用系統 PATH 中的 git。Windows 可填寫 C:\\Program Files\\Git\\cmd\\git.exe。",
      currentInput: "目前輸入",
      savedPath: "已儲存路徑",
      notSaved: "尚未儲存",
      gitStatusInitial: "尚未測試 Git。",
      versionBehaviorTitle: "版本行為",
      defaultNoteLabel: "預設版本說明",
      defaultNoteHelp: "建立版本時說明為空，將使用此預設文字。",
      autoSafetyLabel: "還原舊版本前自動建立安全版本",
      autoSafetyHelp: "建議保持開啟，還原前會先儲存目前檔案，降低誤覆蓋風險。",
      statusTitle: "狀態與排錯",
      pluginVersion: "插件版本",
      supportedFormats: "支援格式",
      supportedFormatsValue: ".docx 正文級識別；.doc 檔案級追蹤",
      dataDirectory: "資料目錄",
      dataDirectoryFallback: "Zotero 設定目錄中的 git4zotero 資料夾",
      trackingHelp: "是否追蹤某個條目由條目清單右鍵選單中的「論文版本」操作控制；右側面板僅顯示狀態。",
      diagnosticsTitle: "診斷與健康檢查",
      diagnosticsDescription: "複製診斷資訊可用於提交 issue；健康檢查只讀取狀態，不會自動修復或清理歷史。",
      firstUseTitle: "首次使用向導",
      firstUseDescription: "適合第一次安裝插件或第一次在新電腦上使用。向導只顯示說明和檢查結果，不會修改論文檔案。",
      openFirstUseGuide: "開啟首次使用向導",
      firstUseGuideTitle: "git4zotero 首次使用向導",
      firstUseGuideBody: "1. 安裝並測試 Git：本插件只用 Git 在本機儲存版本歷史，不要求你會寫程式。\n2. 資料目錄：版本歷史儲存在 Zotero 設定目錄下的 git4zotero 資料夾，不上傳雲端。\n3. 啟用版本管理：在 Zotero 條目清單中右鍵論文條目或附件，選擇「論文版本 → 啟用版本管理」。\n4. 儲存後建立版本：先在 Word/WPS/LibreOffice 中儲存論文，再右鍵選擇「檢查修改」和「建立版本...」。\n5. 格式差異：.docx 支援正文級差異；.doc 只能做檔案級追蹤。",
      firstUseGuideSubtitle: "按步驟檢查必要環境，並可直接執行安全設定和診斷操作。",
      guideClose: "關閉",
      guidePrevious: "上一步",
      guideNext: "下一步",
      guideFinish: "完成",
      guideStatusOk: "正常",
      guideStatusWarning: "需處理",
      guideStatusError: "錯誤",
      guideStatusPending: "待檢查",
      guideStatusChecking: "檢查中",
      guideGitStepTitle: "Git 準備",
      guideGitStepDescription: "確認 Git 可執行檔路徑和可用狀態。git4zotero 只使用本機 Git 儲存版本歷史。",
      guideGitChecking: "正在偵測 Git：{path}",
      guideGitReady: "Git 可用：{detail}\n目前 Git 路徑：{path}",
      guideGitMissing: "Git 暫不可用：{detail}\n目前 Git 路徑：{path}",
      guideDataStepTitle: "資料目錄",
      guideDataStepDescription: "確認插件資料目錄位置和寫入權限。版本歷史儲存在這裡，不改變 Zotero 原始附件。",
      guideDataReady: "插件資料目錄：{path}",
      guideDataFailed: "無法讀取插件資料目錄：{message}",
      guideDataWriteChecking: "正在檢查資料目錄寫入權限...",
      guideDataWriteReady: "寫入權限正常：{path}",
      guideDataWriteFailed: "寫入權限檢查失敗：{message}",
      guideDataActionCheckWrite: "檢查寫入權限",
      guideArchiveStepTitle: "遷移備份",
      guideArchiveStepDescription: "設定「匯出全部版本歷史...」的預設目錄；這不影響匯入位置、Zotero 原始附件或插件資料目錄。",
      guideArchiveReady: "遷移匯出目錄：{path}",
      guideArchiveUnset: "未指定遷移匯出目錄；匯出時將使用系統儲存對話框預設位置。",
      guideArchiveUnavailable: "遷移匯出目錄不可用：{message}",
      guideArchiveActionChoose: "選擇目錄",
      guideTroubleshootingStepTitle: "排錯準備",
      guideTroubleshootingStepDescription: "產生健康檢查和診斷資訊，方便定位 Git、資料目錄和版本倉庫問題。",
      guideTroubleshootingReady: "可執行健康檢查，或複製脫敏診斷資訊和 issue 範本。",
      guideTroubleshootingHealthReady: "健康檢查狀態：\n{summary}",
      guideActionFailed: "操作失敗：{message}",
      lowRiskActionsTitle: "低風險工具",
      openDataDirectory: "開啟資料目錄",
      copyIssueTemplate: "複製 issue 範本",
      openGitGuide: "開啟 Git 安裝指南",
      dataDirectoryOpened: "已開啟資料目錄：{path}",
      dataDirectoryOpenFailed: "無法開啟資料目錄：{message}",
      issueTemplateCopied: "issue 範本已複製到剪貼簿。",
      issueTemplateFallback: "無法寫入剪貼簿，請手動複製下方 issue 範本：\n{template}",
      gitGuideOpened: "已開啟 Git 安裝指南。",
      gitGuideOpenFailed: "無法開啟 Git 安裝指南：{message}",
      archiveActionsTitle: "版本歷史備份與遷移",
      archiveActionsDescription: "匯出/匯入只處理 git4zotero 儲存的本機版本歷史，不包含 Zotero 原始附件檔案。匯入時只合併缺失倉庫，不覆蓋既有歷史。",
      archiveExportDirectoryLabel: "遷移匯出目錄",
      archiveExportDirectoryHelp: "只影響「匯出全部版本歷史」的預設儲存位置；不影響匯入位置，也不改變 Zotero 原始附件或插件資料目錄。",
      archiveExportDirectoryPlaceholder: "未指定，使用系統儲存對話框預設位置",
      archiveExportDirectoryCurrent: "目前遷移匯出目錄",
      archiveExportDirectoryChoose: "選擇目錄...",
      archiveExportDirectoryClear: "清空",
      archiveExportDirectoryChooseTitle: "選擇遷移匯出目錄",
      archiveExportDirectorySaved: "遷移匯出目錄已儲存：{path}",
      archiveExportDirectoryCleared: "已清空遷移匯出目錄，將使用系統儲存對話框預設位置。",
      exportAllHistory: "匯出全部版本歷史...",
      importHistory: "匯入版本歷史...",
      archiveStatusInitial: "尚未匯入或匯出版本歷史。",
      archiveExporting: "正在匯出全部版本歷史...",
      archiveImporting: "正在匯入版本歷史...",
      archiveCanceled: "已取消操作。",
      archiveExportFailed: "匯出版本歷史失敗：{message}",
      archiveImportFailed: "匯入版本歷史失敗：{message}",
      copyDiagnostics: "複製診斷資訊",
      runHealthCheck: "執行健康檢查",
      diagnosticsInitial: "尚未複製診斷資訊。",
      diagnosticsBuilding: "正在產生診斷資訊...",
      diagnosticsCopied: "診斷資訊已複製到剪貼簿。",
      diagnosticsCopyFallback: "無法寫入剪貼簿，請手動複製下方診斷資訊：\n{report}",
      diagnosticsFailed: "診斷資訊產生失敗：{message}",
      healthInitial: "尚未執行健康檢查。",
      healthRunning: "正在執行健康檢查...",
      healthFailed: "健康檢查失敗：{message}",
      healthSummary: "健康檢查完成：正常 {okCount} 項，需要處理 {warningCount} 項，錯誤 {errorCount} 項，跳過 {skippedCount} 項。\n{details}",
      lastErrorTitle: "最近錯誤",
      lastErrorNone: "尚未記錄錯誤。",
      lastErrorSummary: "{time} · {category} · {operation}\n{message}\n建議：{suggestion}",
      healthStatusOk: "正常",
      healthStatusWarning: "需要處理",
      healthStatusError: "錯誤",
      healthStatusSkipped: "跳過",
      healthCheckGit: "測試 Git",
      healthCheckDataDirectory: "檢查資料目錄",
      healthCheckWritePermission: "檢查寫入權限",
      healthCheckDeletedHistory: "掃描已刪除條目歷史",
      healthCheckMetadataSchema: "檢查 metadata schema",
      healthCheckRepositoryConsistency: "檢查 Git/index/metadata 一致性",
      healthGitAvailable: "Git 可用：{detail}",
      healthGitUnavailable: "Git 不可用：{detail}",
      healthDataDirectoryReady: "資料目錄可用：{path}",
      healthDataDirectoryFailed: "資料目錄不可用：{message}",
      healthWritePermissionReady: "寫入權限正常：{path}",
      healthWritePermissionFailed: "寫入權限檢查失敗：{message}",
      healthDeletedHistoryNone: "未發現已刪除條目留下的版本歷史。",
      healthDeletedHistoryFound: "發現 {count} 個已刪除條目留下的版本歷史。",
      healthMetadataSchemaOk: "metadata schema 正常，已檢查 {count} 個倉庫。",
      healthMetadataSchemaIssues: "發現 {count} 個 metadata 問題：{details}",
      healthMetadataSchemaSkipped: "資料目錄不存在，已跳過 metadata schema 檢查。",
      healthRepositoryConsistencyOk: "Git/index/metadata 一致性正常，已檢查 {count} 個倉庫。",
      healthRepositoryConsistencyIssues: "發現 {count} 個一致性問題：{details}",
      healthRepositoryConsistencySkipped: "資料目錄不存在，已跳過一致性檢查。",
      healthSuggestionGit: "建議安裝 Git，或在設定頁填寫正確的 git.exe 路徑後重新測試。",
      healthSuggestionDataDirectory: "建議檢查 Zotero profile 是否可寫，或複製診斷資訊提交 issue。",
      healthSuggestionWritePermission: "建議關閉可能占用目錄的安全軟體或同步軟體，確認 Zotero profile 可寫後重試。",
      healthSuggestionDeletedHistory: "確認條目已不需要恢復後，可使用「清理已刪除條目的歷史」明確清理。",
      healthSuggestionMetadata: "建議先不要手動修改倉庫檔案，複製診斷資訊並提交 issue。",
      healthSuggestionConsistency: "建議先不要手動修復倉庫；複製診斷資訊提交 issue，後續可按明確修復入口處理。",
      checkDeletedHistory: "檢查已刪除條目的歷史",
      cleanDeletedHistory: "清理已刪除條目的歷史",
      orphanInitial: "尚未檢查是否有已刪除條目留下的版本歷史。",
      orphanHelp: "條目移入 Zotero 回收站時，版本歷史會保留，方便恢復條目後繼續使用。若條目已被永久刪除或清空回收站，插件會清理對應歷史；此工具可檢查並清理升級前遺留的無對應條目的歷史。",
      testingGit: "正在測試 Git...",
      gitAvailable: "Git 可用：{detail}\n已測試路徑：{testedPath}\n已儲存路徑：{savedPath}",
      gitUnavailable: "Git 不可用：{detail}",
      gitPathCheckHint: "請檢查 Git 路徑。",
      gitTestFailed: "Git 測試失敗：{message}",
      orphanChecking: "正在檢查是否有已刪除條目留下的版本歷史...",
      orphanCheckFailed: "已刪除條目的歷史檢查失敗：{message}",
      orphanNone: "未發現需要清理的歷史。",
      orphanNoneSkipped: "未發現需要清理的歷史。{count} 個倉庫因路徑或元資料異常被跳過。",
      orphanFound: "發現 {count} 個已刪除條目留下的版本歷史：\n{paths}{more}\n確認這些條目不再需要恢復後，可點擊「清理已刪除條目的歷史」。",
      orphanMore: "\n...另有 {count} 個。",
      orphanCleanTitle: "清理已刪除條目的歷史",
      orphanCleanConfirm: "將刪除 {count} 個 Zotero 中已找不到對應條目的 git4zotero 版本歷史。此操作只刪除插件儲存的歷史，不會修改 Zotero 資料庫，也不會刪除目前論文附件。確定繼續嗎？",
      orphanCleanCanceled: "已取消清理已刪除條目的歷史。",
      orphanCleaning: "正在清理已刪除條目的歷史...",
      orphanCleanFailed: "已刪除條目的歷史清理失敗：{message}",
      orphanCleanSkipped: "已清理 {cleanedCount} 個歷史，{skippedCount} 個因安全校驗未通過而跳過。",
      orphanCleaned: "已清理 {count} 個已刪除條目的版本歷史。"
    }
  }),
  "en-US": buildBundle({
    locale: "en-US",
    dateLocale: "en-US",
    colon: ": ",
    semicolon: "; ",
    listComma: ", ",
    fullStop: ".",
    menuRoot: "Paper Versions",
    loading: "Reading paper version information...",
    noItem: "Select a Zotero item.",
    gitUnavailable: "Git Unavailable",
    gitUnavailableDetail: "No usable Git executable was detected. Install Git or configure the Git executable path.",
    gitPathNotFound: "Git executable not found. Enter the full git.exe path in the Paper Version Management settings, for example C:\\Program Files\\Git\\cmd\\git.exe.",
    gitPathActionRequired: "Git executable not found; enter the full git.exe path",
    gitConfigured: "Git Path Configured",
    configureGit: "Configure Git Path",
    refreshPanel: "Refresh",
    refreshingPanel: "Refreshing...",
    noDocument: "No Manageable Manuscript File Found",
    noDocumentDetail: "Add a .docx or .doc attachment to the current item.",
    rightClickHint: "Right-click an item or manuscript attachment in the item list to use version actions.",
    notEnabled: "Version Management Not Enabled",
    notEnabledDetail: "Only items enabled from the context menu are tracked by git4zotero. Disabled items do not create Git repositories or save and restore versions.",
    enableManagement: "Enable Version Management",
    enablingManagement: "Enabling version management...",
    enableSuccess: "Paper version management has been enabled for the current item.",
    disableManagement: "Disable Version Management",
    disablingManagement: "Disabling version management...",
    disableConfirmTitle: "Disable Version Management",
    disableConfirmMessage: "Existing version history will be kept, but this item will no longer allow checking, creating, or restoring versions. Continue?",
    disableSuccess: "Paper version management has been disabled for the current item.",
    itemNotEnabledError: "Paper version management is not enabled for the current item.",
    currentFile: "Current manuscript file",
    createVersion: "Create Version",
    creatingVersion: "Creating version...",
    checkChanges: "Check Changes",
    checkingChanges: "Checking changes...",
    lastCheck: "Last Check",
    neverChecked: "Changes have not been checked yet.",
    workingTree: "Git Working Tree",
    workingTreeClean: "Working tree has no uncommitted changes.",
    workingTreeUninitialized: "Git repository has not been created yet.",
    versionHistory: "Version History",
    restoreVersion: "Restore This Version",
    restoringVersion: "Restoring version...",
    emptyHistory: "No versions have been created yet.",
    notePlaceholder: "Enter a version note, for example: revised introduction",
    defaultNote: "Paper version",
    safetyNotePrefix: "Automatic backup before restore",
    restoreConfirmTitle: "Restore Paper Version",
    restoreConfirmMessage: "Restore will automatically back up the current file, then overwrite the current manuscript attachment with the selected version. Continue?",
    createSuccess: "Version created.",
    noChangesToSave: "No changes detected; there is no new version to create.",
    restoreSuccess: "Version restored.",
    restoreSafetyBackup: "Current file backup before restore",
    restorePreflightMissing: "The current manuscript file does not exist and cannot be restored.",
    restorePreflightUnreadable: "The current manuscript file cannot be read, so restore cannot proceed safely.",
    restorePreflightUnwritable: "The directory containing the current manuscript file is not writable, so restore cannot proceed safely.",
    restorePreflightWritable: "Current file directory is writable",
    restorePreflightBlocked: "Restore preflight failed, so restore was blocked.",
    restorePreflightWarning: "Restore preflight passed, but there are risks to review. Save and close Word/WPS/LibreOffice before continuing.",
    restorePreflightOk: "Restore preflight passed.",
    restorePreflightChanged: "The current manuscript file changed after confirmation, so restore was canceled. Run restore again.",
    restoreTargetHash: "Target version file hash",
    restoreTargetHashUnknown: "This history record does not include a file hash; the actual Git file will still be verified during restore.",
    restorePreflightTitle: "Pre-Restore Safety Check",
    restorePreflightConfirmIntro: "Review the restore details below. If the file is still open in Word/WPS/LibreOffice, save and close it before continuing.",
    restorePreflightErrors: "Found {count} blocking restore issue(s).",
    restorePreflightWarnings: "Found {count} issue(s) that need attention.",
    restorePreflightProceed: "Continuing will back up the current file first, then replace it with the target version. Continue?",
    restoreFailedWithBackup: "Restore failed; the current file backup was kept.",
    restoreHashMismatch: "The restored file failed validation; git4zotero attempted to roll back to the pre-restore state.",
    repositoryHealth: "Repository Health",
    repositoryHealthOk: "Version repository status is normal.",
    repositoryHealthWarning: "The version repository has issues that need attention.",
    repositoryHealthError: "The version repository has issues that may affect restore.",
    operationFailed: "Operation Failed",
    errorUserActionableTitle: "Action Needed",
    errorGitTitle: "Git Issue",
    errorFileStateTitle: "File State Issue",
    errorInternalTitle: "Internal Plugin Error",
    errorUserActionableSuggestion: "Follow the prompt to select an item, enable version management, or check changes before continuing.",
    errorGitSuggestion: "Make sure Git is installed, enter the correct Git executable path in settings, and test Git again.",
    errorFileStateSuggestion: "Make sure the manuscript file exists, is saved, and is not being held open by Word/WPS/LibreOffice.",
    errorInternalSuggestion: "Copy diagnostics and include the operation steps in an issue so the problem can be located.",
    actionCompleted: "Operation completed.",
    menuUnavailable: "Paper version action unavailable",
    menuMultiSelectUnsupported: "Select only one Zotero item or manuscript attachment.",
    menuCreatePromptTitle: "Create Paper Version",
    menuCreatePromptMessage: "Enter a note for this version.",
    createPreviewTitle: "Confirm Before Creating Version",
    createPreviewConfirmMessage: "Review the version information that will be saved.",
    createPreviewProceed: "Create this version?",
    createPreviewNoChanges: "No saveable changes were detected.",
    createPreviewDocWarning: ".doc is tracked at file level only; this version will not include content-level diff.",
    menuRestorePromptTitle: "Restore Paper Version",
    menuRestorePromptMessage: "Choose the version to restore.",
    menuExportSummary: "Export Version Summary",
    menuExportSummaryLabel: "Export Version Summary...",
    menuExportScopeMessage: "Choose what to export.",
    menuExportFormatMessage: "Choose the export format.",
    exportScopeHistory: "Full Version History",
    exportScopeLastCheck: "Latest Checked Diff",
    exportFormatText: "Plain Text",
    exportSuccess: "Version summary exported.",
    exportNoLastCheck: "Changes have not been checked yet, so the latest checked diff cannot be exported.",
    menuNoVersions: "No versions have been created for the current item.",
    menuStatusLoading: "Reading paper version status...",
    menuStatusNoSelection: "Select an item or manuscript attachment.",
    menuStatusReady: "Paper versions are available.",
    menuStatusNoHistory: "No versions have been created yet.",
    menuDisabledReasonPrefix: "Unavailable",
    menuConfigureGit: "Configure Git Path...",
    invalidCommit: "Invalid version identifier; restore was canceled.",
    promptGitTitle: "Configure Git Path",
    promptGitMessage: "Enter the Git executable path. Leave blank to use git from the system PATH.",
    contentModeDocx: ".docx content-level diff",
    contentModeFileOnly: "File-level tracking",
    docFileOnlyTracking: ".doc supports file-level tracking only. You can create and restore versions, but body text differences are not parsed.",
    versionDetails: "Version Details",
    savedBeforeCheck: "Save the manuscript in Word/WPS/LibreOffice before returning to Zotero to check changes or create a version.",
    stateDirty: "Uncommitted changes",
    stateClean: "Working tree clean",
    stateUnchecked: "Working tree not checked",
    stateEnabled: "Enabled",
    stateDisabled: "Disabled",
    stateGitAvailable: "Git available",
    stateGitUnavailable: "Git unavailable",
    stateLatestVersion: "Latest version",
    stateLastCheck: "Last check",
    stateWorkingTree: "Uncommitted changes",
    statusCardsTitle: "Current Status",
    stateVersionCount: "{count} versions",
    stateLatest: "Latest {value}",
    workflow: "Workflow",
    workflowAddAttachmentTitle: "Add Manuscript Attachment",
    workflowAddAttachmentDetail: "Add a .docx or .doc file to the current item before managing versions.",
    workflowEnableTitle: "Enable Version Management",
    workflowEnableDetail: "Right-click the item or attachment, then choose \"{menuRoot} -> {enableManagement}\".",
    workflowCheckCreateFirstTitle: "Check Changes and Create the First Version",
    workflowCheckCreateFirstCurrentTitle: "Check and Create the First Version",
    workflowCheckCreateFirstDetail: "After enabling, use \"{checkChanges}\" to confirm the diff, then use \"{createVersion}\".",
    workflowEnabledTitle: "Version Management Enabled",
    workflowConfigureGitTitle: "Configure Git",
    workflowConfigureGitDetail: "Open the settings pane to enter the Git path, or right-click and choose \"{menuConfigureGit}\".",
    workflowCheckCurrentTitle: "Check Current Changes",
    workflowCheckSavedDetail: "After saving the manuscript file, right-click and choose \"{checkChanges}\"; once confirmed, choose \"{createVersion}\".",
    workflowRestoreHistoryTitle: "Restore Historical Version",
    workflowRestoreHistoryAvailable: "{count} versions are available. Right-click and choose \"{restoreVersionMenu}\".",
    workflowRestoreHistoryEmpty: "Restorable history will appear here after the first version is created.",
    workflowWorkingTreeTitle: "Working Tree Status",
    workflowWorkingTreeDirty: "Uncommitted changes were detected and will enter history after you create a version.",
    contentSummaryDocx: "Body {paragraphCount} paragraphs · {wordCount} words",
    additionalIssues: "{count} more issues are not expanded.",
    versionNoteLabel: "Version note",
    createdAtLabel: "Created at",
    fileNameLabel: "File name",
    fileSizeLabel: "File size",
    versionTypeLabel: "Version type",
    safetyBackupLabel: "Safety backup",
    changeSummaryLabel: "Change summary",
    trackingModeLabel: "Tracking mode",
    safetyBackupYes: "Yes, automatic backup before restore",
    safetyBackupNo: "No",
    versionKindSafety: "Automatic backup",
    versionKindGit: "Git history",
    versionKindManual: "Manual",
    versionKindSafetyFull: "Automatic backup before restore",
    versionKindManualFull: "Manual version",
    omittedParagraphChanges: "{count} more paragraph changes are not expanded.",
    omittedParagraphChangesDialog: "{count} more paragraph changes are not expanded in this dialog.",
    concreteChanges: "Detailed Changes",
    changeBefore: "Before",
    changeAfter: "After",
    changeDeleted: "Deleted",
    changeAdded: "Added",
    changeKindAdded: "Added paragraph",
    changeKindDeleted: "Deleted paragraph",
    changeKindModified: "Modified paragraph",
    changeKindParagraph: "Paragraph change",
    paragraphIndex: "Paragraph {index}",
    emptyParagraph: "(empty paragraph)",
    sourceDocument: "Body",
    sourceFootnotes: "Footnotes",
    sourceEndnotes: "Endnotes",
    sourceHeader: "Header",
    sourceFooter: "Footer",
    tableLabel: "Table",
    tableWithIndex: "Table {index}",
    untitledBody: "Untitled body",
    changeCount: "{count} changes",
    firstDocxSummary: "First version. A snapshot of the current .docx body content will be saved.",
    noChanges: "No changes detected.",
    fileOnlyFormattingSummary: "Body content did not change; only formatting, styles, metadata, or internal Word state changed.",
    docxContentChanged: "Body content changed",
    addedParagraphs: "Added {count} paragraphs",
    deletedParagraphs: "Deleted {count} paragraphs",
    modifiedParagraphs: "Modified {count} paragraphs",
    wordDelta: "Word delta {value}",
    firstDocxUnreadableSummary: "First version. The current .docx cannot be parsed, so a file-level snapshot was saved.",
    firstFileLevelSummary: "First version. {extension} will be saved as a file-level snapshot.",
    thisFormat: "this format",
    docxReadFailedSummary: "The current .docx cannot be parsed and was saved as a file-level snapshot. Make sure the file has been fully saved by Word/WPS.",
    genericFileLevelSummary: "This format supports file-level detection only: the file changed, but body text differences are not parsed.",
    noDocxByteReader: "The current environment cannot read docx file bytes.",
    missingDocumentXml: "Cannot identify the docx body: word/document.xml is missing.",
    noComparableText: "No comparable text was found in the docx body, footnotes, or endnotes. Make sure the file is saved and contains body text.",
    invalidDocxZipDirectory: "Invalid docx ZIP directory.",
    invalidDocxLocalHeader: "The local header for docx entry {name} is invalid.",
    unsupportedCompressionMethod: "Unsupported compression method: {method}",
    docxEntryInflateFailed: "Cannot parse compressed content for docx entry {name}: {message}",
    docxEntrySizeMismatch: "Inflated length mismatch for docx entry {name}: expected {expected}, got {actual}.",
    missingZipCentralDirectory: "Cannot read docx: ZIP central directory not found.",
    compressedDataUnexpectedEnd: "Compressed data ended unexpectedly.",
    invalidTrackedPath: "Tracked file path is invalid; restore was canceled.",
    gitStatusFailed: "Cannot read Git working tree status.",
    gitCommandFailed: "Git command failed: git {args}",
    processExitCode: "exit code {code}",
    saveFileTitle: "Save File",
    saveDialogUnavailable: "The current environment cannot open the save dialog.",
    saveDialogNoPath: "The save dialog did not return a file path.",
    saveDialogUnsupported: "The current environment does not support the file save dialog.",
    missingIOUtilsGetChildren: "The current Zotero environment lacks IOUtils.getChildren, so the plugin data directory cannot be scanned.",
    missingIOUtils: "The current Zotero environment lacks IOUtils, so manuscript files cannot be accessed.",
    pathSegmentParent: "Path segments cannot contain ..",
    unsafeRepoPath: "Repository path does not match the git4zotero safe path format.",
    repoAlreadyMissing: "Repository directory no longer exists.",
    metadataMismatchCleanup: "Version metadata does not match the delete event; cleanup was skipped.",
    currentAttachment: "Current attachment",
    currentFileMissing: "Current manuscript file does not exist.",
    metadataFile: "Version metadata",
    metadataRecordCount: "schema {schema}, {count} records.",
    metadataVersionsInvalid: "versions in versions.json is not an array.",
    metadataVersions: "Metadata version",
    metadataWillUpgrade: "Current schema {current}; after write it will upgrade to {next}.",
    gitRepository: "Git repository",
    repositoryInitialized: "Initialized.",
    repositoryGitDirMissing: ".git directory not found yet.",
    historyFilePath: "History file path",
    invalidTrackedVersions: "{count} versions are missing restorable tracked file paths.",
    currentTrackedFile: "Current tracked file",
    trackedFileMissing: "The tracked file was not found in the current working tree; historical versions may still be restorable from Git.",
    versionHistoryHealth: "Version history",
    versionHistoryHealthDetail: "{visibleCount} versions readable by the pane; {metadataCount} metadata records.",
    exportTitleHistory: "Version History",
    exportTitleLastCheck: "Latest Checked Diff",
    exportFieldFile: "File",
    exportFieldItem: "Item",
    exportFieldExportedAt: "Exported at",
    exportFieldTime: "Time",
    exportFieldSize: "Size",
    exportFieldType: "Type",
    exportFieldSummary: "Summary",
    exportNoVersions: "No versions have been created yet.",
    exportRecentCheck: "Latest Check",
    exportLocationSummary: "Location Summary",
    exportUnknownSize: "Unknown size",
    yes: "Yes",
    no: "No",
    restoreSafetyCreated: "Automatically backed up before restore: {hash}",
    restoreSafetySkipped: "Automatic backup before restore: not created (setting disabled)",
    restoreTargetVersion: "Target version",
    restoreFile: "File",
    backupPathLabel: "Backup path",
    restoreCannotRestore: "Cannot restore the selected version: {reason}",
    fileDoesNotExist: "Manuscript file does not exist: {path}",
    missingRestorePath: "Historical version is missing a restorable file path.",
    restoreSourceMissing: "Cannot restore the selected version: historical version file does not exist: {path}",
    restoreStagingHashMismatch: "Historical version staging validation failed; restore was canceled.",
    restoreFailedWithBackupPath: "{message} Backup path: {path}. {reason}",
    archiveExportTitle: "Export All Version History",
    archiveImportTitle: "Import Version History",
    archiveExportSuccess: "Version history exported: {path}\nIncluded {repoCount} repositories and {fileCount} files.",
    archiveImportSuccess: "Version history import complete: {importedCount} imported, {skippedCount} skipped, {failedCount} failed.",
    archiveImportSkippedExisting: "Target repository already exists and was not overwritten.",
    archiveInvalidZip: "The backup is not a recognized git4zotero ZIP file.",
    archiveInvalidEntry: "The backup contains an unsafe or unsupported path: {name}",
    archiveNoRepositories: "No importable version repositories were found in the backup.",
    archiveExportDirectoryUnavailable: "Migration export directory is unavailable: {path}",
    archiveExportDirectoryNotFolder: "Migration export path is not a folder: {path}",
    preferences: {
      gitSettingsTitle: "Git Settings",
      gitSettingsDescription: "git4zotero uses local Git to save manuscript attachment versions in the Zotero profile directory.",
      gitPathLabel: "Git executable path",
      testGit: "Test Git",
      gitPathHelp: "Leave blank to use git from the system PATH. On Windows, you can enter C:\\Program Files\\Git\\cmd\\git.exe.",
      currentInput: "Current input",
      savedPath: "Saved path",
      notSaved: "Not saved",
      gitStatusInitial: "Git has not been tested yet.",
      versionBehaviorTitle: "Version Behavior",
      defaultNoteLabel: "Default version note",
      defaultNoteHelp: "If the version note is empty when creating a version, this default text will be used.",
      autoSafetyLabel: "Automatically create a safety version before restoring an old version",
      autoSafetyHelp: "Recommended. The current file is saved before restore to reduce accidental overwrite risk.",
      statusTitle: "Status and Troubleshooting",
      pluginVersion: "Plugin version",
      supportedFormats: "Supported formats",
      supportedFormatsValue: ".docx content-level diff; .doc file-level tracking",
      dataDirectory: "Data directory",
      dataDirectoryFallback: "git4zotero folder in the Zotero profile directory",
      trackingHelp: "Tracking is controlled by the Paper Versions context menu in the item list; the right pane only displays status.",
      diagnosticsTitle: "Diagnostics and Health Check",
      diagnosticsDescription: "Copy diagnostics for issue reports; the health check only reads status and will not repair or clean history automatically.",
      firstUseTitle: "First-Use Guide",
      firstUseDescription: "Use this when installing the plugin for the first time or setting up a new computer. The guide only shows instructions and checks; it does not modify manuscript files.",
      openFirstUseGuide: "Open First-Use Guide",
      firstUseGuideTitle: "git4zotero First-Use Guide",
      firstUseGuideBody: "1. Install and test Git: this plugin only uses Git to save local version history; you do not need to write code.\n2. Data directory: version history is stored in the git4zotero folder under your Zotero profile and is not uploaded to the cloud.\n3. Enable version management: in the Zotero item list, right-click the manuscript item or attachment and choose \"Paper Versions -> Enable Version Management\".\n4. Create versions after saving: save the manuscript in Word/WPS/LibreOffice, then right-click and choose \"Check Changes\" and \"Create Version...\".\n5. Format limits: .docx supports content-level diffs; .doc is file-level tracking only.",
      firstUseGuideSubtitle: "Check the required environment step by step and run safe setup or diagnostic actions directly.",
      guideClose: "Close",
      guidePrevious: "Previous",
      guideNext: "Next",
      guideFinish: "Finish",
      guideStatusOk: "OK",
      guideStatusWarning: "Needs attention",
      guideStatusError: "Error",
      guideStatusPending: "Pending",
      guideStatusChecking: "Checking",
      guideGitStepTitle: "Git Setup",
      guideGitStepDescription: "Confirm the Git executable path and availability. git4zotero only uses local Git to save version history.",
      guideGitChecking: "Checking Git: {path}",
      guideGitReady: "Git is available: {detail}\nCurrent Git path: {path}",
      guideGitMissing: "Git is not available yet: {detail}\nCurrent Git path: {path}",
      guideDataStepTitle: "Data Directory",
      guideDataStepDescription: "Confirm the plugin data directory and write permission. Version history is stored here without changing original Zotero attachments.",
      guideDataReady: "Plugin data directory: {path}",
      guideDataFailed: "Could not read the plugin data directory: {message}",
      guideDataWriteChecking: "Checking data directory write permission...",
      guideDataWriteReady: "Write permission is available: {path}",
      guideDataWriteFailed: "Write permission check failed: {message}",
      guideDataActionCheckWrite: "Check Write Permission",
      guideArchiveStepTitle: "Migration Backup",
      guideArchiveStepDescription: "Configure the default directory for \"Export All Version History...\"; this does not affect imports, original Zotero attachments, or the plugin data directory.",
      guideArchiveReady: "Migration export directory: {path}",
      guideArchiveUnset: "No migration export directory is set; exports will use the system save dialog default.",
      guideArchiveUnavailable: "Migration export directory is unavailable: {message}",
      guideArchiveActionChoose: "Choose Directory",
      guideTroubleshootingStepTitle: "Troubleshooting",
      guideTroubleshootingStepDescription: "Generate health checks and diagnostics to locate Git, data directory, and version repository issues.",
      guideTroubleshootingReady: "You can run a health check, or copy redacted diagnostics and the issue template.",
      guideTroubleshootingHealthReady: "Health check status:\n{summary}",
      guideActionFailed: "Action failed: {message}",
      lowRiskActionsTitle: "Low-Risk Tools",
      openDataDirectory: "Open Data Directory",
      copyIssueTemplate: "Copy Issue Template",
      openGitGuide: "Open Git Install Guide",
      dataDirectoryOpened: "Opened data directory: {path}",
      dataDirectoryOpenFailed: "Could not open data directory: {message}",
      issueTemplateCopied: "Issue template copied to the clipboard.",
      issueTemplateFallback: "Clipboard write failed. Copy the issue template below manually:\n{template}",
      gitGuideOpened: "Opened the Git install guide.",
      gitGuideOpenFailed: "Could not open the Git install guide: {message}",
      archiveActionsTitle: "Version History Backup and Migration",
      archiveActionsDescription: "Export/import handles only local version history saved by git4zotero and does not include Zotero's original attachment files. Import only merges missing repositories and never overwrites existing history.",
      archiveExportDirectoryLabel: "Migration export directory",
      archiveExportDirectoryHelp: "Only affects the default save location for Export All Version History; it does not affect imports, original Zotero attachments, or the plugin data directory.",
      archiveExportDirectoryPlaceholder: "Not set; use the system save dialog default",
      archiveExportDirectoryCurrent: "Current migration export directory",
      archiveExportDirectoryChoose: "Choose Directory...",
      archiveExportDirectoryClear: "Clear",
      archiveExportDirectoryChooseTitle: "Choose Migration Export Directory",
      archiveExportDirectorySaved: "Migration export directory saved: {path}",
      archiveExportDirectoryCleared: "Migration export directory cleared; the system save dialog default will be used.",
      exportAllHistory: "Export All Version History...",
      importHistory: "Import Version History...",
      archiveStatusInitial: "Version history has not been imported or exported yet.",
      archiveExporting: "Exporting all version history...",
      archiveImporting: "Importing version history...",
      archiveCanceled: "Operation canceled.",
      archiveExportFailed: "Version history export failed: {message}",
      archiveImportFailed: "Version history import failed: {message}",
      copyDiagnostics: "Copy Diagnostics",
      runHealthCheck: "Run Health Check",
      diagnosticsInitial: "Diagnostics have not been copied yet.",
      diagnosticsBuilding: "Building diagnostics...",
      diagnosticsCopied: "Diagnostics copied to the clipboard.",
      diagnosticsCopyFallback: "Clipboard write failed. Copy the diagnostics below manually:\n{report}",
      diagnosticsFailed: "Diagnostics failed: {message}",
      healthInitial: "Health check has not run yet.",
      healthRunning: "Running health check...",
      healthFailed: "Health check failed: {message}",
      healthSummary: "Health check complete: {okCount} normal, {warningCount} need attention, {errorCount} errors, {skippedCount} skipped.\n{details}",
      lastErrorTitle: "Recent Error",
      lastErrorNone: "No error has been recorded yet.",
      lastErrorSummary: "{time} · {category} · {operation}\n{message}\nSuggestion: {suggestion}",
      healthStatusOk: "Normal",
      healthStatusWarning: "Needs attention",
      healthStatusError: "Error",
      healthStatusSkipped: "Skipped",
      healthCheckGit: "Test Git",
      healthCheckDataDirectory: "Check data directory",
      healthCheckWritePermission: "Check write permission",
      healthCheckDeletedHistory: "Scan history for deleted items",
      healthCheckMetadataSchema: "Check metadata schema",
      healthCheckRepositoryConsistency: "Check Git/index/metadata consistency",
      healthGitAvailable: "Git available: {detail}",
      healthGitUnavailable: "Git unavailable: {detail}",
      healthDataDirectoryReady: "Data directory is available: {path}",
      healthDataDirectoryFailed: "Data directory is unavailable: {message}",
      healthWritePermissionReady: "Write permission is available: {path}",
      healthWritePermissionFailed: "Write permission check failed: {message}",
      healthDeletedHistoryNone: "No version history left by deleted items was found.",
      healthDeletedHistoryFound: "Found {count} version histories left by deleted items.",
      healthMetadataSchemaOk: "Metadata schema is normal; checked {count} repositories.",
      healthMetadataSchemaIssues: "Found {count} metadata issues: {details}",
      healthMetadataSchemaSkipped: "Data directory does not exist; metadata schema check was skipped.",
      healthRepositoryConsistencyOk: "Git/index/metadata consistency is normal; checked {count} repositories.",
      healthRepositoryConsistencyIssues: "Found {count} consistency issues: {details}",
      healthRepositoryConsistencySkipped: "Data directory does not exist; consistency check was skipped.",
      healthSuggestionGit: "Install Git, or enter the correct git.exe path in settings and test again.",
      healthSuggestionDataDirectory: "Check whether the Zotero profile is writable, or copy diagnostics and file an issue.",
      healthSuggestionWritePermission: "Close security or sync software that may be locking the directory, confirm the Zotero profile is writable, then retry.",
      healthSuggestionDeletedHistory: "After confirming the item no longer needs to be restored, use \"Clean History for Deleted Items\" to clean it explicitly.",
      healthSuggestionMetadata: "Do not edit repository files manually; copy diagnostics and file an issue.",
      healthSuggestionConsistency: "Do not repair the repository manually; copy diagnostics and file an issue so a future explicit repair action can be designed.",
      checkDeletedHistory: "Check History for Deleted Items",
      cleanDeletedHistory: "Clean History for Deleted Items",
      orphanInitial: "History left by deleted items has not been checked yet.",
      orphanHelp: "When an item is moved to the Zotero trash, version history is kept so it can continue to be used if the item is restored. If an item is permanently deleted or the trash is emptied, git4zotero cleans its history. This tool checks and cleans legacy history that no longer has a matching item.",
      testingGit: "Testing Git...",
      gitAvailable: "Git available: {detail}\nTested path: {testedPath}\nSaved path: {savedPath}",
      gitUnavailable: "Git unavailable: {detail}",
      gitPathCheckHint: "Check the Git path.",
      gitTestFailed: "Git test failed: {message}",
      orphanChecking: "Checking for version history left by deleted items...",
      orphanCheckFailed: "History check for deleted items failed: {message}",
      orphanNone: "No history needs cleanup.",
      orphanNoneSkipped: "No history needs cleanup. {count} repositories were skipped because the path or metadata was abnormal.",
      orphanFound: "Found {count} version histories left by deleted items:\n{paths}{more}\nAfter confirming these items no longer need to be restored, click \"Clean History for Deleted Items\".",
      orphanMore: "\n...and {count} more.",
      orphanCleanTitle: "Clean History for Deleted Items",
      orphanCleanConfirm: "This will delete {count} git4zotero version histories whose corresponding Zotero items can no longer be found. This only deletes plugin-saved history; it will not modify the Zotero database or delete current manuscript attachments. Continue?",
      orphanCleanCanceled: "Cleanup of history for deleted items was canceled.",
      orphanCleaning: "Cleaning history for deleted items...",
      orphanCleanFailed: "Cleanup of history for deleted items failed: {message}",
      orphanCleanSkipped: "Cleaned {cleanedCount} histories; {skippedCount} were skipped because safety checks failed.",
      orphanCleaned: "Cleaned {count} version histories left by deleted items."
    }
  })
});

export function resolveUILocale(locale) {
  const normalized = String(locale || "").trim().toLowerCase();
  if (normalized === "zh-cn" || normalized === "zh-sg" || normalized.startsWith("zh-hans")) {
    return "zh-CN";
  }
  if (normalized === "zh-tw" || normalized === "zh-hk" || normalized === "zh-mo" || normalized.startsWith("zh-hant")) {
    return "zh-TW";
  }
  if (normalized.startsWith("en")) {
    return "en-US";
  }
  return normalized.startsWith("zh") ? "zh-CN" : "en-US";
}

export function setUILocale(locale) {
  const resolved = resolveUILocale(locale);
  const bundle = UI_TEXT_BUNDLES[resolved] || UI_TEXT_BUNDLES["en-US"];
  for (const key of Object.keys(UI_TEXT)) {
    delete UI_TEXT[key];
  }
  Object.assign(UI_TEXT, cloneText(bundle));
  return UI_TEXT.locale;
}

export function getUILocale() {
  return UI_TEXT.locale || "zh-CN";
}

export function formatText(key, values = {}) {
  return formatTemplate(getTextValue(key), values);
}

export function formatTemplate(template, values = {}) {
  return String(template ?? "").replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => {
    return Object.prototype.hasOwnProperty.call(values, key) ? String(values[key]) : match;
  });
}

function getTextValue(key) {
  return String(key).split(".").reduce((value, part) => value?.[part], UI_TEXT) ?? key;
}

function buildBundle(overrides) {
  return {
    ...ZH_CN_TEXT,
    ...overrides,
    preferences: {
      ...ZH_CN_TEXT.preferences,
      ...(overrides.preferences || {})
    }
  };
}

function cloneText(value) {
  if (Array.isArray(value)) {
    return value.map(cloneText);
  }
  if (value && typeof value === "object") {
    return Object.fromEntries(Object.entries(value).map(([key, child]) => [key, cloneText(child)]));
  }
  return value;
}
